In [1]:
## Marital

## Looking over variables, looks like we'll have:
# marital_det (full set of data categories), marital (narrowest set)
 
# look at impacts on voting behaviour (maybe some categories matter more)
# try to impute missing values

In [2]:
# %%time
## Just an easy way to load utility functions
dataset_name = "W19_only"
df_list = []

import pickle
# from scipy import integrate
%matplotlib inline 
%run f2f_header.py {dataset_name} {df_list}

global BES_label_list, BES_df_list

BES_df_list = pickle.load( open( "E:\\BES_analysis_data\\Face_to_face\\BES_df_list.pickle", "rb" ) )
f2f_harmonised = pd.read_pickle("E:\\BES_analysis_data\\Face_to_face\\f2f_harmonised_temp.zip", compression='zip')
BES_label_list = pickle.load( open( "E:\\BES_analysis_data\\Face_to_face\\BES_label_list.pickle", "rb" ) )
demo_var_dict = pickle.load( open( "E:\\BES_analysis_data\\Face_to_face\\demo_var_dict.pickle", "rb" ) )
var_type_dict_nonans = pickle.load( open( "E:\\BES_analysis_data\\Face_to_face\\var_type_dict_nonans.pickle", "rb" ) )

generic_cols = f2f_harmonised.columns
list_of_scale_harm_vars = ["Age","year_past_min_sch_leave_age","in_school_past_min_age"]

%run f2f_utility.py

In [136]:
marital_dict = {
    'single':"SINGLE",'single,never married':"SINGLE",'not married':"SINGLE",'never married':"SINGLE",
        'single (never married)':"SINGLE","Single":"SINGLE",6:"SINGLE",
    'living as married':"MARRIED",'common law marriag':"MARRIED",'living with a partner':"MARRIED",'Living with partner':"MARRIED",
        'Living with partner, not legally registered partnership':"MARRIED",2:"MARRIED",
    'married/living as married':"MARRIED",
    "married woman":"MARRIED","married man":"MARRIED",'married':"MARRIED",'Married':"MARRIED",
        'Married/in a registered civil partnership':"MARRIED",1:"MARRIED",
    "separated":"DIVWIDSEP","Separated":"DIVWIDSEP",3:"DIVWIDSEP",
    "divorced":"DIVWIDSEP","Divorced":"DIVWIDSEP",4:"DIVWIDSEP",
    'widowed':"DIVWIDSEP","Widowed":"DIVWIDSEP",5:"DIVWIDSEP",
    'separated or divorced after marrying':"DIVWIDSEP",'separated (after being married)':"DIVWIDSEP",
    "divorced":"DIVWIDSEP",'widowed or separated':"DIVWIDSEP",'divorced separated':"DIVWIDSEP",
    'divorced/separated':"DIVWIDSEP",'separated/divorced':"DIVWIDSEP",
    'refused':np.nan,0:np.nan,'not answered':np.nan,'not     answered':np.nan,'no information':np.nan,"don't   know":np.nan,
        'not app':np.nan,'Not stated':np.nan, 'Prefer not to say':np.nan,8:np.nan,9999:np.nan,
    
}
marital_det_dict = {
    'single':"SINGLE",'single,never married':"SINGLE",'not married':"SINGLE",'never married':"SINGLE",
        'single (never married)':"SINGLE","Single":"SINGLE",6:"SINGLE",
    'living as married':"COHAB",'common law marriag':"COHAB",'living with a partner':"COHAB",'Living with partner':"COHAB",
        'Living with partner, not legally registered partnership':"COHAB",2:"COHAB",
    'married/living as married':"MARRIED/COH",
    "married woman":"MARRIED","married man":"MARRIED",'married':"MARRIED",'Married':"MARRIED",
        'Married/in a registered civil partnership':"MARRIED",1:"MARRIED",
    "separated":"SEPARATED","Separated":"SEPARATED",'separated (after being married)':"SEPARATED",3:"SEPARATED",
    "divorced":"DIVORCED","Divorced":"DIVORCED","divorced":"DIVORCED",4:"DIVORCED",
    'widowed':"WIDOWED","Widowed":"WIDOWED",5:"WIDOWED",
    'widowed or separated':"WID/SEPAR",
    'divorced separated':"DIV/SEPAR",'separated or divorced after marrying':"DIV/SEPAR",
        'divorced/separated':"DIV/SEPAR",'separated/divorced':"DIV/SEPAR",
    'refused':np.nan,0:np.nan,'not answered':np.nan,'not     answered':np.nan,'no information':np.nan,"don't   know":np.nan,
        'not app':np.nan,'Not stated':np.nan, 'Prefer not to say':np.nan,8:np.nan,9999:np.nan,
    
}

In [137]:
f2f_harmonised["marital"] = np.nan
f2f_harmonised["marital_det"] = np.nan

ge="2019"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["y26"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["y26"].replace(marital_det_dict)

ge="2017"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["y26"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["y26"].replace(marital_det_dict)

ge="2015"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["y26"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["y26"].replace(marital_det_dict)

ge="2010"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["zq90"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["zq90"].replace(marital_det_dict)

ge="2005"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["tq78"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["tq78"].replace(marital_det_dict)

ge="2001"
temp1 = BES_df_list[ge]["aq39"].replace(marital_dict)
temp2 = BES_df_list[ge]["bq73"].replace(marital_dict)
temp1.loc[temp1.isnull()]=temp2.loc[temp1.isnull()]
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = temp1
temp1 = BES_df_list[ge]["aq39"].replace(marital_det_dict)
temp2 = BES_df_list[ge]["bq73"].replace(marital_det_dict)
temp1.loc[temp1.isnull()]=temp2.loc[temp1.isnull()]
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = temp1

ge="1997"
# marstat2 has same data, but best granularity
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["marstat2"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["marstat2"].replace(marital_det_dict)

ge="1992"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["v906a"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["v906a"].replace(marital_det_dict)

ge="1987"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["v51a"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["v51a"].replace(marital_det_dict)

ge="1983"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["q54a"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["q54a"].replace(marital_det_dict)

ge="1979"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["m200262"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["m200262"].replace(marital_det_dict)

ge="1974_oct"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["oct200"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["oct200"].replace(marital_det_dict)

ge="1974_feb"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["feb200"].replace(marital_dict)
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["feb200"].replace(marital_det_dict)

ge="1964"
temp1 = BES_df_list[ge]['v933'].replace({1:"SINGLE",2:"MARRIED",3:"DIVWIDSEP",9:np.nan})
temp2 = BES_df_list[ge]['v934'].replace({0:np.nan,1:"SINGLE",2:"MARRIED",3:"DIVWIDSEP",9:np.nan})
temp1.loc[temp1.isnull()]=temp2.loc[temp1.isnull()]
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = temp1
###

ge="1966"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]['v935'].replace({0:np.nan,1:"SINGLE",2:"MARRIED",3:"DIVWIDSEP",4:"DIVWIDSEP",5:"DIVWIDSEP",9:np.nan})
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]['v935'].replace({0:np.nan,1:"SINGLE",2:"MARRIED",3:"SEPARATED",4:"WIDOWED",5:"DIVORCED",9:np.nan})

ge="1970"
f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]['v936'].replace({0:np.nan,1:"SINGLE",2:"MARRIED",3:"DIVWIDSEP",9:np.nan})


# f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["feb200"].replace(marital_det_dict)

# ge="1959"
# f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital"] = BES_df_list[ge]["feb200"].replace(marital_dict)
# f2f_harmonised.loc[f2f_harmonised["dataset"]==ge,"marital_det"] = BES_df_list[ge]["feb200"].replace(marital_det_dict)

In [138]:
f2f_harmonised["marital"].value_counts()

MARRIED      30116
SINGLE        8362
DIVWIDSEP     8214
Name: marital, dtype: int64

In [139]:
f2f_harmonised["marital_det"].value_counts()

MARRIED      24951
SINGLE        7927
WIDOWED       4053
COHAB         2353
DIVORCED      2031
SEPARATED      713
DIV/SEPAR      665
WID/SEPAR      290
Name: marital_det, dtype: int64

In [113]:
f2f_harmonised["dataset"].unique()

array(['2019', '2017', '2015', '2010', '2005', '2001', '1997', '1992',
       '1987', '1983', '1979', '1974_feb', '1974_oct', '1970', '1966',
       '1964', '1959'], dtype=object)

In [3]:
[(ge,{k:v for k,v in BES_label_list[ge].items() if  re.search("marital".lower(),v.lower())}) for ge in f2f_harmonised["dataset"].unique()]

[('2019', {'y26': 'Marital status'}),
 ('2017', {'y26': 'Marital Status'}),
 ('2015', {'y26': 'Marital Status'}),
 ('2010',
  {'aq64': 'marital status',
   'bq90': 'marital status(3rd)',
   'zq90': 'marital status(4th)'}),
 ('2005',
  {'aq49': 'marital status',
   'bq78': 'marital status(3rd)',
   'tq78': 'combined-marital status'}),
 ('2001', {'aq39': 'marital status', 'bq73': 'marital status(2nd)'}),
 ('1997',
  {'marstat2': 'marital status of respondent [full]  q639',
   'marstat': 'marital status  dv q640',
   'married': 'marital status [grouped] dv q641'}),
 ('1992', {'v906a': "r's marital status?                q906a"}),
 ('1987', {'v51a': "respondent's marital status"}),
 ('1983', {'q54a': "respondent's marital status"}),
 ('1979', {'m200262': "r's marital status-q97"}),
 ('1974_feb', {'feb200': 'marital status of respondent'}),
 ('1974_oct', {'oct200': 'marital status of respondent'}),
 ('1970',
  {'v933': 'MARITAL STATUS      1963',
   'v934': 'MARITAL STATUS      1964',
   'v935': 'MARITAL STATUS      1966',
   'v936': 'MARITAL STATUS      1970'}),
 ('1966',
  {'v933': 'MARITAL STATUS      1963',
   'v934': 'MARITAL STATUS      1964',
   'v935': 'MARITAL STATUS      1966',
   'v936': 'MARITAL STATUS      1970'}),
 ('1964',
  {'v933': 'MARITAL STATUS      1963',
   'v934': 'MARITAL STATUS      1964',
   'v935': 'MARITAL STATUS      1966',
   'v936': 'MARITAL STATUS      1970'}),
 ('1959',
  {'v933': 'MARITAL STATUS      1963',
   'v934': 'MARITAL STATUS      1964',
   'v935': 'MARITAL STATUS      1966',
   'v936': 'MARITAL STATUS      1970'})]

0       2.0
1       2.0
2       2.0
3       2.0
4       2.0
       ...
2917    9.0
2918    9.0
2919    9.0
2920    9.0
2921    9.0
Name: v933, Length: 2922, dtype: float64

In [43]:
ge="2019"
BES_df_list[ge]['y26'].value_counts()

Married/in a registered civil partnership                  1770
Single                                                      868
Living with partner, not legally registered partnership     465
Widowed                                                     373
Divorced                                                    305
Separated                                                    86
Prefer not to say                                            75
Not stated                                                    4
Name: y26, dtype: int64

In [ ]:
['Not stated', 'Prefer not to say',
       'Married/in a registered civil partnership',
       'Living with partner, not legally registered partnership', 'Single',
       'Widowed', 'Separated', 'Divorced']

['Married', 'Living with partner', 'Single', 'Widowed', 'Separated',
       'Divorced']

['refused', 'married', 'living with a partner',
       'separated (after being married)', 'divorced', 'widowed',
       'single (never married)']

['married', 'living as married', 'separated', 'divorced', 'widowed',
       'never married', 'not app']

['married' < 'living as married' < 'separated (after being married)' < 'divorced' < 'widowed' < 'single (never married)' < 'don't   know' < 'not     answered']
['married' < 'living as married' < 'separated or divorced after marrying' < 'widowed' < 'not married' < 'don't   know' < 'not     answered']
['married/living as married' < 'separated/divorced' < 'widowed' < 'never married' < 'no information']
 
['married' < 'living as married' < 'widowed' < 'divorced/separated' < 'not married' < 'not     answered']
 
['married' < 'living as married' < 'widowed' < 'divorced/separated' < 'not married' < 'not answered']
 
['married' < 'widowed' < 'divorced separated' < 'single']

[0 < 'single,never married' < 'divorced separated' < 'widowed' < 'married' < 'common law marriag' < 'refused']
 
['single' < 'married man' < 'married woman' < 'refused']
 
['single' < 'married woman' < 'married man' < 'divorced' < 'widowed or separated']

['Not stated', 'Prefer not to say',
       'Married/in a registered civil partnership',
       'Living with partner, not legally registered partnership', 'Single',
       'Widowed', 'Separated', 'Divorced']

# ['Married', 'Living with partner', 'Single', 'Widowed', 'Separated',
#        'Divorced']

marital_dict = {
    'single':"SINGLE",'single,never married':"SINGLE",'not married':"SINGLE",'never married':"SINGLE",
        'single (never married)':"SINGLE","Single":"SINGLE",6:"SINGLE",
    'living as married':"MARRIED",'common law marriag':"MARRIED",'living with a partner':"MARRIED",'Living with partner':"MARRIED",
        'Living with partner, not legally registered partnership':"MARRIED",2:"MARRIED",
    'married/living as married':"MARRIED",
    "married woman":"MARRIED","married man":"MARRIED",'married':"MARRIED",'Married':"MARRIED",
        'Married/in a registered civil partnership':"MARRIED",1:"MARRIED",
    "separated":"DIVWIDSEP","Separated":"DIVWIDSEP",3:"DIVWIDSEP",
    "divorced":"DIVWIDSEP","Divorced":"DIVWIDSEP",4:"DIVWIDSEP",
    'widowed':"DIVWIDSEP","Widowed":"DIVWIDSEP",5:"DIVWIDSEP",
    'separated or divorced after marrying':"DIVWIDSEP",'separated (after being married)':"DIVWIDSEP",
    "divorced":"DIVWIDSEP",'widowed or separated':"DIVWIDSEP",'divorced separated':"DIVWIDSEP",
    'divorced/separated':"DIVWIDSEP",'separated/divorced':"DIVWIDSEP",
    'refused':np.nan,0:np.nan,'not answered':np.nan,'not     answered':np.nan,'no information':np.nan,"don't   know":np.nan,
        'not app':np.nan,'Not stated':np.nan, 'Prefer not to say':np.nan,8:np.nan,9999:np.nan,
    
}
marital_det_dict = {
    'single':"SINGLE",'single,never married':"SINGLE",'not married':"SINGLE",'never married':"SINGLE",
        'single (never married)':"SINGLE","Single":"SINGLE",6:"SINGLE",
    'living as married':"COHAB",'common law marriag':"COHAB",'living with a partner':"COHAB",'Living with partner':"COHAB",
        'Living with partner, not legally registered partnership':"COHAB",2:"COHAB",
    'married/living as married':"MARRIED/COH",
    "married woman":"MARRIED","married man":"MARRIED",'married':"MARRIED",'Married':"MARRIED",
        'Married/in a registered civil partnership':"MARRIED",1:"MARRIED",
    "separated":"SEPARATED","Separated":"SEPARATED",'separated (after being married)':"SEPARATED",3:"SEPARATED",
    "divorced":"DIVORCED","Divorced":"DIVORCED","divorced":"DIVORCED",4:"DIVORCED",
    'widowed':"WIDOWED","Widowed":"WIDOWED",5:"WIDOWED",
    'widowed or separated':"WID/SEPAR",
    'divorced separated':"DIV/SEPAR",'separated or divorced after marrying':"DIV/SEPAR",
        'divorced/separated':"DIV/SEPAR",'separated/divorced':"DIV/SEPAR",
    'refused':np.nan,0:np.nan,'not answered':np.nan,'not     answered':np.nan,'no information':np.nan,"don't   know":np.nan,
        'not app':np.nan,'Not stated':np.nan, 'Prefer not to say':np.nan,8:np.nan,9999:np.nan,
    
}

In [ ]:
# 2005
1       2034
2        372
3        146
4        383
5        518
6        703
8          3
9999       2

1 Married
2 Living with a partner
3 Separated (after being married)
4 Divorced
5 Widowed
6 Single (never married)

In [ ]:
# 1963
1.0     256
2.0    1503
3.0     250
9.0     913
1.SINGLE
2.MARRIED
3.WIDOWED/DIVORCED/SEPARATED
9.RESP NOT INT
0.NA
# 1964
0.0       5
1.0     226
2.0    1403
3.0     194
9.0    1094
1.SINGLE
2.MARRIED
3.WIDOWED/DIVORCED/SEPARATED
9.RESP NOT INT
0.NA
# 1966
0.0       1
1.0     243
2.0    1606
3.0      11
4.0     212
5.0       9
9.0     840
1. SINGLE
2. MARRIED
3. SEPARATED
4. WIDOWED
5. DIVORCED
9. RESP NOT INT
0. NA
# 1970
1.0     116
2.0    1064
3.0     175
9.0    1567
1.SINGLE
2.MARRIED
3.WIDOWED/DIVORCED/SEPARATED
9.RESP NOT INT
0.NA

In [140]:
f2f_harmonised["AuthRight"] = f2f_harmonised["bloc_complete"]=="Right-Auth"
f2f_harmonised["LibLeft"] = f2f_harmonised["bloc_complete"]=="Left-Lib"
f2f_harmonised["DNV"] = f2f_harmonised["vote_complete_simple"]=="DNV"

In [141]:
pd.get_dummies(f2f_harmonised[["marital","bloc_complete"]]).corr()

,marital_DIVWIDSEP,marital_MARRIED,marital_SINGLE,bloc_complete_Left-Lib,bloc_complete_Neither,bloc_complete_Right-Auth
marital_DIVWIDSEP,1.000000,-0.495695,-0.186479,0.002393,0.019845,-0.012105
marital_MARRIED,-0.495695,1.000000,-0.500974,0.065948,-0.099960,0.033148
marital_SINGLE,-0.186479,-0.500974,1.000000,-0.008727,0.112011,-0.077961
bloc_complete_Left-Lib,0.002393,0.065948,-0.008727,1.000000,-0.449889,-0.660475
bloc_complete_Neither,0.019845,-0.099960,0.112011,-0.449889,1.000000,-0.343437
bloc_complete_Right-Auth,-0.012105,0.033148,-0.077961,-0.660475,-0.343437,1.000000

In [143]:
pd.get_dummies(f2f_harmonised[["marital_det","bloc_complete"]]).corr().round(2)

,marital_det_COHAB,marital_det_DIV/SEPAR,marital_det_DIVORCED,marital_det_MARRIED,marital_det_SEPARATED,marital_det_SINGLE,marital_det_WID/SEPAR,marital_det_WIDOWED,bloc_complete_Left-Lib,bloc_complete_Neither,bloc_complete_Right-Auth
marital_det_COHAB,1.00,-0.02,-0.04,-0.20,-0.03,-0.09,-0.02,-0.06,-0.01,0.08,-0.05
marital_det_DIV/SEPAR,-0.02,1.00,-0.02,-0.11,-0.01,-0.05,-0.01,-0.03,0.01,-0.01,-0.01
marital_det_DIVORCED,-0.04,-0.02,1.00,-0.19,-0.02,-0.08,-0.01,-0.06,0.00,0.04,-0.03
marital_det_MARRIED,-0.20,-0.11,-0.19,1.00,-0.11,-0.40,-0.07,-0.27,0.06,-0.11,0.04
marital_det_SEPARATED,-0.03,-0.01,-0.02,-0.11,1.00,-0.05,-0.01,-0.03,-0.00,0.05,-0.04
marital_det_SINGLE,-0.09,-0.05,-0.08,-0.40,-0.05,1.00,-0.03,-0.12,-0.01,0.12,-0.08
marital_det_WID/SEPAR,-0.02,-0.01,-0.01,-0.07,-0.01,-0.03,1.00,-0.02,-0.00,-0.00,0.01
marital_det_WIDOWED,-0.06,-0.03,-0.06,-0.27,-0.03,-0.12,-0.02,1.00,0.00,-0.02,0.02
bloc_complete_Left-Lib,-0.01,0.01,0.00,0.06,-0.00,-0.01,-0.00,0.00,1.00,-0.45,-0.66
bloc_complete_Neither,0.08,-0.01,0.04,-0.11,0.05,0.12,-0.00,-0.02,-0.45,1.00,-0.34
bloc_complete_Right-Auth,-0.05,-0.01,-0.03,0.04,-0.04,-0.08,0.01,0.02,-0.66,-0.34,1.00

In [148]:
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1959","marital_det"] = f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital_det"]
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1959","marital"] = f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital"]

In [168]:
# marital_59=f2f_harmonised.loc[f2f_harmonised["dataset"]=="1959","marital"]
marital_64=f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital"]
marital_66=f2f_harmonised.loc[f2f_harmonised["dataset"]=="1966","marital"]
marital_70=f2f_harmonised.loc[f2f_harmonised["dataset"]=="1970","marital"]

df = pd.concat([marital_64,marital_66,marital_70],axis=1)
df.columns = ["marital_64","marital_66","marital_70"]
df = df.fillna(method='ffill',axis=1).fillna(method='bfill',axis=1)

f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital"] = df["marital_64"]
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1966","marital"] = df["marital_66"]
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1970","marital"] = df["marital_70"]
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1959","marital"] = f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital"]

marital_64=f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital_det"]
marital_66=f2f_harmonised.loc[f2f_harmonised["dataset"]=="1966","marital_det"]
marital_70=f2f_harmonised.loc[f2f_harmonised["dataset"]=="1970","marital_det"]

df = pd.concat([marital_64,marital_66,marital_70],axis=1)
df.columns = ["marital_64","marital_66","marital_70"]
df = df.fillna(method='ffill',axis=1).fillna(method='bfill',axis=1)

f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital_det"] = df["marital_64"]
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1966","marital_det"] = df["marital_66"]
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1970","marital_det"] = df["marital_70"]
f2f_harmonised.loc[f2f_harmonised["dataset"]=="1959","marital_det"] = f2f_harmonised.loc[f2f_harmonised["dataset"]=="1964","marital_det"]

In [ ]:
### imputation!

In [170]:
married_cols = f2f_harmonised[["marital","marital_det"]].copy()
married_cols.to_pickle("E:\\BES_analysis_data\\Face_to_face\\married_cols.zip", compression='zip')