In [1]:
%%time
%matplotlib inline
%run Prosser_header.py

dataset_folder = "C:\\Users\\Marios\\Documents\\GitHub\\Thomas Prosser project\\datasets\\"
output_folder  = "C:\\Users\\Marios\\Documents\\GitHub\\Thomas Prosser project\\output\\"

Wall time: 3.03 s

In [141]:
CSES_int_final = pd.read_pickle(dataset_folder + "CSES"+os.sep+"Integration"+os.sep+"CSES_int_final.pkl")

def get_dta_meta(fn):
    reader = pd.io.stata.StataReader( fn )
    header = reader.variable_labels()
    labels = reader.value_labels()
    return header,labels
headerINT,labelsINT = get_dta_meta(dataset_folder + "CSES"+os.sep+"integrated 1-4"+os.sep+"cses_imd.dta")

variable_manifest = pd.read_csv(dataset_folder + "CSES"+os.sep+"Integration"+os.sep+"variable_manifest.csv",index_col="Unnamed: 0")

cses_variable_types = pd.read_pickle(dataset_folder + "CSES"+os.sep+"Integration"+os.sep+"cses_variable_types.pkl")

party_ref = party_ref_final = pd.read_csv(dataset_folder + "CSES"+os.sep+"Integration"+os.sep+"party_ref_final.csv",index_col="Unnamed: 0")

In [18]:
variable_manifest["variable structural type"].value_counts()

respondent    96
party         90
country       87
dataset        3
empty          1
Name: variable structural type, dtype: int64

In [32]:
country_vars = list(variable_manifest[variable_manifest["variable structural type"]=="country"]["index"])
party_vars = list(variable_manifest[variable_manifest["variable structural type"]=="party"]["index"])
respondent_vars = list(variable_manifest[variable_manifest["variable structural type"]=="respondent"]["index"])
dataset_vars = list(variable_manifest[variable_manifest["variable structural type"]=="dataset"]["index"])

In [28]:
# election_study_level_dataset[election_study_level_dataset["IMD1006_NAM"]=="Greece"]

## Greece election studies fixed!

In [33]:
election_study_level_dataset = CSES_int_final[country_vars+dataset_vars].drop_duplicates().sort_values("IMD1003").set_index("IMD1003")
election_study_level_dataset

,IMD1004,IMD1006,IMD1006_UN,IMD1006_NAM,IMD1008_YEAR,IMD1008_MOD_1,IMD1008_MOD_2,IMD1008_MOD_3,IMD1008_MOD_4,IMD1009,...,IMD5057_2,IMD5057_3,IMD5058_1,IMD5058_2,IMD5059_1,IMD5059_2,IMD1008_MOD_5,IMD1001,IMD1002_VER,IMD1002_DOI
IMD1003,,,,,,,,,,,,,,,,,,,,,
00802005. ALBANIA (2005),ALB_2005,0080,008,Albania,2005,00. NOT IN CSES MODULE 1,01. IN CSES MODULE 2,00. NOT IN CSES MODULE 3,00. NOT IN CSES MODULE 4,10. PARLIAMENTARY/LEGISLATIVE,...,3026939,3039616,10.46,999.00. MISSING,3.75,999.00. MISSING,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
03202015. ARGENTINA (2015),ARG_2015,0320,032,Argentina,2015,00. NOT IN CSES MODULE 1,00. NOT IN CSES MODULE 2,00. NOT IN CSES MODULE 3,01. IN CSES MODULE 4,12. PARLIAMENTARY/LEGISLATIVE AND PRESIDENTIAL,...,42980024,42538304,3.4,3.4,3.52,3.48,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
03601996. AUSTRALIA (1996),AUS_1996,0360,036,Australia,1996,01. IN CSES MODULE 1,00. NOT IN CSES MODULE 2,00. NOT IN CSES MODULE 3,00. NOT IN CSES MODULE 4,10. PARLIAMENTARY/LEGISLATIVE,...,18072000,17855000,3.21,999.00. MISSING,2.62,999.00. MISSING,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
03602004. AUSTRALIA (2004),AUS_2004,0360,036,Australia,2004,00. NOT IN CSES MODULE 1,01. IN CSES MODULE 2,00. NOT IN CSES MODULE 3,00. NOT IN CSES MODULE 4,10. PARLIAMENTARY/LEGISLATIVE,...,19895400,19651400,3.17,999.00. MISSING,2.44,999.00. MISSING,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
03602007. AUSTRALIA (2007),AUS_2007,0360,036,Australia,2007,00. NOT IN CSES MODULE 1,00. NOT IN CSES MODULE 2,01. IN CSES MODULE 3,00. NOT IN CSES MODULE 4,10. PARLIAMENTARY/LEGISLATIVE,...,20697900,20394800,3.03,3.03,2.43,2.43,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84002004. UNITED STATES (2004),USA_2004,8400,840,United States of America,2004,00. NOT IN CSES MODULE 1,01. IN CSES MODULE 2,00. NOT IN CSES MODULE 3,00. NOT IN CSES MODULE 4,12. PARLIAMENTARY/LEGISLATIVE AND PRESIDENTIAL,...,290107933,287625193,2.18,999.00. MISSING,2,999.00. MISSING,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
84002008. UNITED STATES (2008),USA_2008,8400,840,United States of America,2008,00. NOT IN CSES MODULE 1,00. NOT IN CSES MODULE 2,01. IN CSES MODULE 3,00. NOT IN CSES MODULE 4,12. PARLIAMENTARY/LEGISLATIVE AND PRESIDENTIAL,...,301580000,298592992,2.16,2.15,1.94,1.94,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
84002016. UNITED STATES (2016),USA_2016,8400,840,United States of America,2016,00. NOT IN CSES MODULE 1,00. NOT IN CSES MODULE 2,00. NOT IN CSES MODULE 3,00. NOT IN CSES MODULE 4,12. PARLIAMENTARY/LEGISLATIVE AND PRESIDENTIAL,...,321039840,318622528,999.00. MISSING,999.00. MISSING,999.00. MISSING,999.00. MISSING,01. IN CSES MODULE 5,CSES-MODULE-5,VER2020-MAY-14,doi:10.7804/cses.module5.2020-05-14
84022012. UNITED STATES (2012),USA_2012,8402,840,United States of America,2012,00. NOT IN CSES MODULE 1,00. NOT IN CSES MODULE 2,00. NOT IN CSES MODULE 3,01. IN CSES MODULE 4,12. PARLIAMENTARY/LEGISLATIVE AND PRESIDENTIAL,...,311582560,309326304,2.19,2.19,1.99,1.99,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17
85802009. URUGUAY (2009),URY_2009,8580,858,Uruguay,2009,00. NOT IN CSES MODULE 1,00. NOT IN CSES MODULE 2,01. IN CSES MODULE 3,00. NOT IN CSES MODULE 4,12. PARLIAMENTARY/LEGISLATIVE AND PRESIDENTIAL,...,3334052,3323906,2.75,2.75,2.65,2.65,00. NOT IN CSES MODULE 5,CSES-IMD,VER2019-OCT-17,doi:10.7804/cses.imd.2019-10-17

In [84]:
respondent_vars_level_dataset

,IMD1005,IMD1007,IMD1008_RES,IMD1010_1,IMD1010_2,IMD1010_3,IMD1013_M,IMD1013_D,IMD1013_Y,IMD1014_1,...,IMD3013_3,IMD3014,IMD3015_1,IMD3015_2,IMD3015_3,IMD3015_4,IMD3015_A,IMD3015_B,IMD3015_C,IMD3015_D
0,008020050000001111,001. [SEE ELECTION STUDY NOTES],0000001111,1.0000,1.0000,1.0,07. JULY,99. MISSING,2005,9999. MISSING,...,9. MISSING,3. BAD JOB,1. CORRECT,1. CORRECT,0. INCORRECT,9. MISSING,9. MISSING,2,9. MISSING,9. MISSING
1,008020050000001112,001. [SEE ELECTION STUDY NOTES],0000001112,1.0000,1.0000,1.0,07. JULY,99. MISSING,2005,9999. MISSING,...,9. MISSING,2. GOOD JOB,8. VOLUNTEERED: DON'T KNOW,8. VOLUNTEERED: DON'T KNOW,8. VOLUNTEERED: DON'T KNOW,9. MISSING,9. MISSING,0,9. MISSING,9. MISSING
2,008020050000001113,001. [SEE ELECTION STUDY NOTES],0000001113,1.0000,1.0000,1.0,07. JULY,99. MISSING,2005,9999. MISSING,...,9. MISSING,2. GOOD JOB,1. CORRECT,0. INCORRECT,1. CORRECT,9. MISSING,9. MISSING,2,9. MISSING,9. MISSING
3,008020050000001114,001. [SEE ELECTION STUDY NOTES],0000001114,1.0000,1.0000,1.0,07. JULY,99. MISSING,2005,9999. MISSING,...,9. MISSING,2. GOOD JOB,1. CORRECT,0. INCORRECT,0. INCORRECT,9. MISSING,9. MISSING,1,9. MISSING,9. MISSING
4,008020050000001115,001. [SEE ELECTION STUDY NOTES],0000001115,1.0000,1.0000,1.0,07. JULY,99. MISSING,2005,9999. MISSING,...,9. MISSING,2. GOOD JOB,8. VOLUNTEERED: DON'T KNOW,0. INCORRECT,8. VOLUNTEERED: DON'T KNOW,9. MISSING,9. MISSING,0,9. MISSING,9. MISSING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316243,840020160000005085,001. [SEE ELECTION STUDY NOTES],0000005085,1.1308,1.1308,1.0,11. NOVEMBER,17,2016,9,...,9. MISSING,2. GOOD JOB,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING
316244,840020160000005086,001. [SEE ELECTION STUDY NOTES],0000005086,0.8032,0.8032,1.0,11. NOVEMBER,11,2016,3,...,9. MISSING,1. VERY GOOD JOB,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING
316245,840020160000005087,001. [SEE ELECTION STUDY NOTES],0000005087,1.4443,1.4443,1.0,11. NOVEMBER,9,2016,1,...,9. MISSING,3. BAD JOB,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING
316246,840020160000005088,001. [SEE ELECTION STUDY NOTES],0000005088,3.7257,3.7257,1.0,11. NOVEMBER,22,2016,14,...,9. MISSING,1. VERY GOOD JOB,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING
316247,840020160000005089,001. [SEE ELECTION STUDY NOTES],0000005089,1.1683,1.1683,1.0,11. NOVEMBER,18,2016,10,...,9. MISSING,1. VERY GOOD JOB,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING,9. MISSING

In [108]:
# base variables for the full set of party variabes _A ... _I
cses_to_partyfacts_final = party_ref.set_index("cses_party_id")["partyfacts_id_min_tech"]

party_base_variables = ['IMD5000', 'IMD5001', 'IMD5002', 'IMD5003', 'IMD5004', 'IMD5005', 'IMD5011', 'IMD5012', 'IMD5029', 'IMD5031']
party_level = CSES_int_final[party_vars].groupby(CSES_int_final["IMD1003"]).first()

df = pd.melt( party_level[ search( party_level , 'IMD5000' ).index].reset_index(),
         id_vars = ["IMD1003"])
for base in party_base_variables[1:]:
    df[base] = pd.melt( party_level[ search( party_level , base ).index].reset_index(),
         id_vars = ["IMD1003"])["value"]

df["value"] = df["value"].apply(lambda x: cses_to_partyfacts_final.loc[x])
df = df[df["value"].notnull()]
df["value"] = df["value"].astype(int)

column_rename = {
 "variable":"party_letter",
 "value":"partyfacts_id",   
#  "IMD1003": "ELECTION STUDY ID",
#  'IMD5000': 'PARTY IDENTIFIER',
#  'IMD5001': 'PERCENT VOTE - LOWER HOUSE',
#  'IMD5002': 'PERCENT SEATS - LOWER HOUSE',
#  'IMD5003': 'PERCENT VOTE - UPPER HOUSE',
#  'IMD5004': 'PERCENT SEATS - UPPER HOUSE',
#  'IMD5005': 'PERCENT VOTE - PRESIDENT',
#  'IMD5011': 'IDEOLOGICAL FAMILY',
#  'IMD5012': 'LEFT-RIGHT',
#  'IMD5029': 'NUMBER OF PORTFOLIOS BEFORE',
#  'IMD5031': 'NUMBER OF PORTFOLIOS AFTER'
}

df = df.rename(columns=column_rename)
df["party_letter"] = df["party_letter"].apply(lambda x: x.split("_")[1])
df["ELECTION YEAR"] = df["IMD1003"].apply(lambda x: int(x.split("(")[1][0:4]))
df["COUNTRY"] = df["IMD1003"].apply(lambda x: x.split(". ")[1].split("(")[0].strip())
# BELGIUM-FLANDERS     6
# BELGIUM-WALLONIA     4

party_level_dataset = df.copy()

In [109]:
party_level_dataset

,IMD1003,party_letter,partyfacts_id,IMD5001,IMD5002,IMD5003,IMD5004,IMD5005,IMD5011,IMD5012,IMD5029,IMD5031,ELECTION YEAR,COUNTRY
0,00802005. ALBANIA (2005),A,190,44.06,40,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION,9. CONSERVATIVE PARTIES,6,0,12,2005,ALBANIA
1,03202015. ARGENTINA (2015),A,2530,37.4,43.85,32.72,54.17,997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION,5. LEFT LIBERAL PARTIES,4,21,0,2015,ARGENTINA
2,03601996. AUSTRALIA (1996),A,424,38.7,33.1,36.1,38.1,996. NOT APPLICABLE: NO ROLE OF PRESIDENT,4. SOCIAL DEMOCRATIC PARTIES,4.5,999. MISSING,999. MISSING,1996,AUSTRALIA
3,03602004. AUSTRALIA (2004),A,1998,40.47,50,43.37,45,996. NOT APPLICABLE: NO ROLE OF PRESIDENT,7. RIGHT LIBERAL PARTIES,6,14,14,2004,AUSTRALIA
4,03602007. AUSTRALIA (2007),A,424,43.38,55.33,40.3,45,996. NOT APPLICABLE: NO ROLE OF PRESIDENT,4. SOCIAL DEMOCRATIC PARTIES,3,0,21,2007,AUSTRALIA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1717,64302004. RUSSIA (2004),I,7409,997. NOT APPLICABLE: NO LOWER HOUSE ELECTION,997. NOT APPLICABLE: NO LOWER HOUSE ELECTION,997. NOT APPLICABLE: NO UPPER HOUSE ELECTION,997. NOT APPLICABLE: NO UPPER HOUSE ELECTION,0.76,90. OTHER,99. MISSING,999. MISSING,999. MISSING,2004,RUSSIA
1720,70302016. SLOVAKIA (2016),I,63,4.94,0,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION,8. CHRISTIAN DEMOCRATIC PARTIES,8,0,0,2016,SLOVAKIA
1733,75202006. SWEDEN (2006),I,1240,999. MISSING,999. MISSING,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: NO ROLE OF PRESIDENT,99. MISSING,99. MISSING,999. MISSING,999. MISSING,2006,SWEDEN
1734,75202014. SWEDEN (2014),I,1240,3.12,0,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: NO ROLE OF PRESIDENT,90. OTHER,2,0,0,2014,SWEDEN
1742,79202011. TURKEY (2011),I,1740,0.25,0,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION,4. SOCIAL DEMOCRATIC PARTIES,4,0,0,2011,TURKEY

In [132]:
party_level_dataset.columns

Index(['IMD1003', 'party_letter', 'partyfacts_id', 'IMD5001', 'IMD5002',
       'IMD5003', 'IMD5004', 'IMD5005', 'IMD5011', 'IMD5012', 'IMD5029',
       'IMD5031', 'ELECTION YEAR', 'COUNTRY'],
      dtype='object')

In [142]:

variable_manifest.loc[variable_manifest.index.max()+1]=["party_letter",9,'object','object',"dataset letter key",
                                        "Top 9 party ref",list(party_level_dataset["party_letter"].unique()),
                                        "meta","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["partyfacts_id",len(party_level_dataset['partyfacts_id'].unique()),
                                        'int32','int32',"Partyfacts Id",
                                        "Partyfacts Id",list(party_level_dataset["partyfacts_id"].unique()),
                                        "meta","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5001",len(party_level_dataset['IMD5001'].unique()),
                                        'object','category',"PERCENT VOTE - LOWER HOUSE",
                                        "Voteshare - Lower House",list(party_level_dataset["IMD5001"].unique()),
                                        "seminumeric","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5002",len(party_level_dataset['IMD5002'].unique()),
                                        'object','category',"PERCENT SEATS - LOWER HOUSE",
                                        "Seatshare - Lower House",list(party_level_dataset["IMD5002"].unique()),
                                        "seminumeric","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5003",len(party_level_dataset['IMD5003'].unique()),
                                        'object','category',"PERCENT VOTE - UPPER HOUSE",
                                        "Voteshare - Upper House",list(party_level_dataset["IMD5003"].unique()),
                                        "seminumeric","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5004",len(party_level_dataset['IMD5004'].unique()),
                                        'object','category',"PERCENT SEATS - UPPER HOUSE",
                                        "Seatshare - Upper House",list(party_level_dataset["IMD5004"].unique()),
                                        "seminumeric","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5005",len(party_level_dataset['IMD5005'].unique()),
                                        'object','category',"PERCENT VOTE - PRESIDENT",
                                        "Voteshare - President",list(party_level_dataset["IMD5005"].unique()),
                                        "seminumeric","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5011",len(party_level_dataset['IMD5011'].unique()),
                                        'object','category',"IDEOLOGICAL FAMILY",
                                        "Ideological Family",list(party_level_dataset["IMD5011"].unique()),
                                        "dummy","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5012",len(party_level_dataset['IMD5012'].unique()),
                                        'object','category',"LEFT-RIGHT",
                                        "Left-Right",list(party_level_dataset["IMD5012"].unique()),
                                        "seminumeric","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5029",len(party_level_dataset['IMD5029'].unique()),
                                        'object','category',"NUMBER OF PORTFOLIOS BEFORE",
                                        "No Portfolios Before Election",list(party_level_dataset["IMD5029"].unique()),
                                        "seminumeric","party"]
variable_manifest.loc[variable_manifest.index.max()+1]=["IMD5031",len(party_level_dataset['IMD5031'].unique()),
                                        'object','category',"NUMBER OF PORTFOLIOS AFTER",
                                        "No Portfolios After Election",list(party_level_dataset["IMD5031"].unique()),
                                        "seminumeric","party"]

564

In [115]:
party_level_dataset.dtypes

IMD1003          object
party_letter     object
partyfacts_id     int32
IMD5001          object
IMD5002          object
IMD5003          object
IMD5004          object
IMD5005          object
IMD5011          object
IMD5012          object
IMD5029          object
IMD5031          object
ELECTION YEAR     int64
COUNTRY          object
dtype: object

,index,un_val_len,final_dtypes,original_dtypes,descr,Short Description,0,variable type,variable structural type
238,IMD5031_A,38,object,category,NUMBER OF PORTFOLIOS AFTER - PARTY A,No. Portfolios After Election Party A,12|0|999. MISSING|14|21|16|7|5|13|9|15|23|38|3...,seminumeric,party

In [114]:
party_level_dataset.describe(include='all')

,IMD1003,party_letter,partyfacts_id,IMD5001,IMD5002,IMD5003,IMD5004,IMD5005,IMD5011,IMD5012,IMD5029,IMD5031,ELECTION YEAR,COUNTRY
count,1270,1270,1270.000000,1270,1270.0,1270,1270,1270,1270,1270.0,1270.0,1270.0,1270.000000,1270
unique,195,9,NaN,836,629.0,201,163,167,28,19.0,36.0,39.0,NaN,57
top,57802013. NORWAY (2013),A,NaN,997. NOT APPLICABLE: NO LOWER HOUSE ELECTION,0.0,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION,4. SOCIAL DEMOCRATIC PARTIES,7.0,0.0,0.0,NaN,MEXICO
freq,9,191,NaN,93,105.0,586,586,595,207,171.0,702.0,668.0,NaN,50
mean,NaN,NaN,1758.044882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2007.650394,NaN
std,NaN,NaN,1751.237640,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.290497,NaN
min,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1996.000000,NaN
25%,NaN,NaN,591.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002.000000,NaN
50%,NaN,NaN,1241.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN
75%,NaN,NaN,1997.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN
max,NaN,NaN,8268.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN

,index,un_val_len,final_dtypes,original_dtypes,descr,Short Description,0,variable type,variable structural type
0,IMD1001,2,object,object,dataset,Dataset Name,CSES-IMD|CSES-MODULE-5,meta,dataset
1,IMD1002_VER,2,object,object,DATASET VERSION,Dataset Version,VER2019-OCT-17|VER2020-MAY-14,meta,dataset
2,IMD1002_DOI,2,object,object,DIGITAL OBJECT IDENTIFIER,Digital Object Identifier,doi:10.7804/cses.imd.2019-10-17|doi:10.7804/cs...,meta,dataset
3,IMD1003,194,object,category,ID VARIABLE - ELECTION STUDY (NUMERIC POLITY),Study Id No,"['00802005. ALBANIA (2005)', '03202015. ARGENT...",meta,country
4,IMD1004,194,object,object,ID VARIABLE - ELECTION STUDY (ALPHABETIC POLITY),Study Id Name,"['ALB_2005', 'ARG_2015', 'AUS_1996', 'AUS_2004...",meta,country
...,...,...,...,...,...,...,...,...,...
272,IMD5058_1,148,object,category,EFFECTIVE NUMBER OF ELECTORAL PARTIES,Effective Number of Electoral Parties,"['10.46', '3.4', '3.21', '3.17', '3.03', '3.42...",seminumeric,country
273,IMD5058_2,108,object,category,CORRECTED EFFECTIVE NUMBER OF ELECTORAL PARTIES,Corrected Effective Number of Electoral Parties,"['999.00. MISSING', '3.4', '3.03', '3.42', '4....",seminumeric,country
274,IMD5059_1,149,object,category,EFFECTIVE NUMBER OF PARLIAMENTARY PARTIES,Effective Number of Parliamentary Parties,"['3.75', '3.52', '2.62', '2.44', '2.43', '2.36...",seminumeric,country
275,IMD5059_2,106,object,category,CORRECTED EFFECTIVE NUMBER OF PARLIAMENTARY PA...,Corrected Effective Number of Parliamentary Pa...,"['999.00. MISSING', '3.48', '2.43', '2.36', '4...",seminumeric,country
276,IMD1008_MOD_5,2,category,category,ID COMPONENT - CSES MODULE 4,Module 5,00. NOT IN CSES MODULE 5|01. IN CSES MODULE 5,meta,country

In [120]:
variable_manifest["variable type"].value_counts()

seminumeric    112
ordinal         73
party           31
dummy           25
meta            20
date            15
drop             1
Name: variable type, dtype: int64

In [40]:
# 999. MISSING                                     2401
# 0.0                                              1456
# 996. NOT APPLICABLE: UNICAMERAL SYSTEM           1350
# 997. NOT APPLICABLE: NO UPPER HOUSE ELECTION     1074
# 99. MISSING                                       862
# 997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION     689
# 996. NOT APPLICABLE: NO ROLE OF PRESIDENT         540
# 9999999. MISSING                                  357
# 997. NOT APPLICABLE: NO LOWER HOUSE ELECTION      288
# 97. NOT APPLICABLE                                 40

missing_vals = ["999. MISSING","996. NOT APPLICABLE: UNICAMERAL SYSTEM","997. NOT APPLICABLE: NO UPPER HOUSE ELECTION",
 "99. MISSING","997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION","996. NOT APPLICABLE: NO ROLE OF PRESIDENT",
 "9999999. MISSING","997. NOT APPLICABLE: NO LOWER HOUSE ELECTION","97. NOT APPLICABLE",0]

replace_dict = dict(zip(missing_vals,[np.nan]*len(missing_vals)))

In [41]:
## bunch of 0s in IMD5029, IMD5031 (min. portfolios before/after by party) which should be missing (because party identifier columns registers missing!)
## -> minor bug

# 37602006. ISRAEL (2006)	IMD5000_G: IMD5031 -> 2 ??? BUG!

# 15201999. CHILE (1999)	IMD5000_E: IMD5005 -> .4
# 44001997. LITHUANIA (1997)	IMD5000_F	IMD5000_E: IMD5005 -> .9
# Maybe they included data before dropping parties by 

## safe to drop all rows with missing party identifier

discrepant_not_nulls = df[df["value"]=="9999999. MISSING"][party_base_variables[1:]].replace(replace_dict).notnull()
df[df["value"]=="9999999. MISSING"][ discrepant_not_nulls.any(axis=1) ]

,IMD1003,variable,value,IMD5001,IMD5002,IMD5003,IMD5004,IMD5005,IMD5011,IMD5012,IMD5029,IMD5031
807,15201999. CHILE (1999),IMD5000_E,9999999. MISSING,997. NOT APPLICABLE: NO LOWER HOUSE ELECTION,997. NOT APPLICABLE: NO LOWER HOUSE ELECTION,997. NOT APPLICABLE: NO UPPER HOUSE ELECTION,997. NOT APPLICABLE: NO UPPER HOUSE ELECTION,0.4,97. NOT APPLICABLE,97. NOT APPLICABLE,999. MISSING,999. MISSING
1081,44001997. LITHUANIA (1997),IMD5000_F,9999999. MISSING,997. NOT APPLICABLE: NO LOWER HOUSE ELECTION,997. NOT APPLICABLE: NO LOWER HOUSE ELECTION,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,0.9,97. NOT APPLICABLE,97. NOT APPLICABLE,999. MISSING,999. MISSING
1143,72402000. SPAIN (2000),IMD5000_F,9999999. MISSING,999. MISSING,999. MISSING,999. MISSING,999. MISSING,996. NOT APPLICABLE: NO ROLE OF PRESIDENT,13. REGIONAL PARTIES,99. MISSING,999. MISSING,999. MISSING
1258,37602006. ISRAEL (2006),IMD5000_G,9999999. MISSING,999. MISSING,999. MISSING,996. NOT APPLICABLE: UNICAMERAL SYSTEM,996. NOT APPLICABLE: UNICAMERAL SYSTEM,997. NOT APPLICABLE: NO PRESIDENTIAL ELECTION,99. MISSING,99. MISSING,0,2

In [63]:
### save X-level datasets to pkls

### save any new variables to variable manifest (e.g. party level generic variables)

# Not so sure how

In [97]:
respondent_vars_level_dataset = CSES_int_final[["IMD1003"]+respondent_vars].copy()

In [98]:
election_study_level_dataset.to_pickle(dataset_folder + "CSES"+os.sep+"Integration"+os.sep+"election_study_level_dataset.pkl")
respondent_vars_level_dataset.to_pickle(dataset_folder + "CSES"+os.sep+"Integration"+os.sep+"respondent_vars_level_dataset.pkl")
party_level_dataset.to_pickle(dataset_folder + "CSES"+os.sep+"Integration"+os.sep+"party_level_dataset.pkl")

In [ ]:
#  "IMD1003": "ELECTION STUDY ID",
#  'IMD5000': 'PARTY IDENTIFIER',
#  'IMD5001': 'PERCENT VOTE - LOWER HOUSE',
#  'IMD5002': 'PERCENT SEATS - LOWER HOUSE',
#  'IMD5003': 'PERCENT VOTE - UPPER HOUSE',
#  'IMD5004': 'PERCENT SEATS - UPPER HOUSE',
#  'IMD5005': 'PERCENT VOTE - PRESIDENT',
#  'IMD5011': 'IDEOLOGICAL FAMILY',
#  'IMD5012': 'LEFT-RIGHT',
#  'IMD5029': 'NUMBER OF PORTFOLIOS BEFORE',
#  'IMD5031': 'NUMBER OF PORTFOLIOS AFTER'

,index,un_val_len,final_dtypes,original_dtypes,descr,Short Description,0,variable type,variable structural type
0,IMD1001,2,object,object,dataset,Dataset Name,CSES-IMD|CSES-MODULE-5,meta,dataset
1,IMD1002_VER,2,object,object,DATASET VERSION,Dataset Version,VER2019-OCT-17|VER2020-MAY-14,meta,dataset
2,IMD1002_DOI,2,object,object,DIGITAL OBJECT IDENTIFIER,Digital Object Identifier,doi:10.7804/cses.imd.2019-10-17|doi:10.7804/cs...,meta,dataset
3,IMD1003,194,object,category,ID VARIABLE - ELECTION STUDY (NUMERIC POLITY),Study Id No,"['00802005. ALBANIA (2005)', '03202015. ARGENT...",meta,country
4,IMD1004,194,object,object,ID VARIABLE - ELECTION STUDY (ALPHABETIC POLITY),Study Id Name,"['ALB_2005', 'ARG_2015', 'AUS_1996', 'AUS_2004...",meta,country
...,...,...,...,...,...,...,...,...,...
272,IMD5058_1,148,object,category,EFFECTIVE NUMBER OF ELECTORAL PARTIES,Effective Number of Electoral Parties,"['10.46', '3.4', '3.21', '3.17', '3.03', '3.42...",seminumeric,country
273,IMD5058_2,108,object,category,CORRECTED EFFECTIVE NUMBER OF ELECTORAL PARTIES,Corrected Effective Number of Electoral Parties,"['999.00. MISSING', '3.4', '3.03', '3.42', '4....",seminumeric,country
274,IMD5059_1,149,object,category,EFFECTIVE NUMBER OF PARLIAMENTARY PARTIES,Effective Number of Parliamentary Parties,"['3.75', '3.52', '2.62', '2.44', '2.43', '2.36...",seminumeric,country
275,IMD5059_2,106,object,category,CORRECTED EFFECTIVE NUMBER OF PARLIAMENTARY PA...,Corrected Effective Number of Parliamentary Pa...,"['999.00. MISSING', '3.48', '2.43', '2.36', '4...",seminumeric,country
276,IMD1008_MOD_5,2,category,category,ID COMPONENT - CSES MODULE 4,Module 5,00. NOT IN CSES MODULE 5|01. IN CSES MODULE 5,meta,country

In [87]:
cses_variable_types

                                                   description variable type
IMD1001                                                dataset       dataset
IMD1002_VER                                    DATASET VERSION       dataset
IMD1002_DOI                          DIGITAL OBJECT IDENTIFIER       dataset
IMD1003          ID VARIABLE - ELECTION STUDY (NUMERIC POLITY)       country
IMD1004       ID VARIABLE - ELECTION STUDY (ALPHABETIC POLITY)       country
...                                                        ...           ...
IMD5057_3            POPULATION, TOTAL (WORLD BANK) - TIME T-2       country
IMD5058_1                EFFECTIVE NUMBER OF ELECTORAL PARTIES       country
IMD5058_2      CORRECTED EFFECTIVE NUMBER OF ELECTORAL PARTIES       country
IMD5059_1            EFFECTIVE NUMBER OF PARLIAMENTARY PARTIES       country
IMD5059_2    CORRECTED EFFECTIVE NUMBER OF PARLIAMENTARY PA...       country

[276 rows x 2 columns]

In [172]:
a,b,c = tuple([1,2,3])
a

1

In [358]:
missing_narrow = ["99. MISSING","9999. MISSING"]
missing_narrow_dict = dict(zip(missing_narrow,[np.nan]*len(missing_narrow)))

CSES_int_final[ flatten( [[x+y for y in base_date_dict[x]] for x in base_date_dict.keys()] ) ].replace(missing_narrow_dict).isnull().sum()

IMD1011_D         0
IMD1011_M         0
IMD1011_Y         0
IMD1012_D         0
IMD1012_M         0
IMD1012_Y         0
IMD1013_D     31574
IMD1013_M     22400
IMD1013_Y     11236
IMD5024_2    127235
IMD5024_1    127235
IMD5024_3    127235
IMD5025_2         0
IMD5025_1         0
IMD5025_3         0
dtype: int64

In [298]:
missing_nonapp = ["96. NOT APPLICABLE: NO SECOND ROUND","9996. NOT APPLICABLE: NO SECOND ROUND"]
missing_nonapp_dict = dict(zip(missing_nonapp,[np.nan]*len(missing_nonapp)))

CSES_int_final[ flatten( [[x+y for y in base_date_dict[x]] for x in base_date_dict.keys()] ) ].replace(missing_nonapp_dict).isnull().sum()

IMD1011_D         0
IMD1011_M         0
IMD1011_Y         0
IMD1012_D    268733
IMD1012_M    268733
IMD1012_Y    268733
IMD1013_D         0
IMD1013_M         0
IMD1013_Y         0
IMD5024_2         0
IMD5024_1         0
IMD5024_3         0
IMD5025_2         0
IMD5025_1         0
IMD5025_3         0
dtype: int64

In [364]:
missing = ["96. NOT APPLICABLE: NO SECOND ROUND","99. MISSING","9996. NOT APPLICABLE: NO SECOND ROUND","9999. MISSING"]
missing_dict = dict(zip(missing,[np.nan]*len(missing)))

CSES_int_final[ flatten( [[x+y for y in base_date_dict[x]] for x in base_date_dict.keys()] ) ].replace(missing_dict).isnull().sum()
#.stack().value_counts().head(50)

# 96. NOT APPLICABLE: NO SECOND ROUND      537466
# 99. MISSING                              323479
# 9996. NOT APPLICABLE: NO SECOND ROUND    268733
# 9999. MISSING                            138471

IMD1011_D         0
IMD1011_M         0
IMD1011_Y         0
IMD1012_D    268733
IMD1012_M    268733
IMD1012_Y    268733
IMD1013_D     31574
IMD1013_M     22400
IMD1013_Y     11236
IMD5024_2    127235
IMD5024_1    127235
IMD5024_3    127235
IMD5025_2         0
IMD5025_1         0
IMD5025_3         0
dtype: int64

In [368]:
CSES_int_final[ CSES_int_final["IMD5024_3"].replace(missing_dict).isnull()&CSES_int_final["IMD5024_3"].replace(missing_dict).isnull() ]["IMD1003"].unique()

array(['00802005. ALBANIA (2005)', '03601996. AUSTRALIA (1996)',
       '03602004. AUSTRALIA (2004)', '03602007. AUSTRALIA (2007)',
       '05611999. BELGIUM-FLANDERS (1999)',
       '05621999. BELGIUM-WALLONIA (1999)', '05602003. BELGIUM (2003)',
       '10002001. BULGARIA(2001)', '11202001. BELARUS (2001)',
       '07602002. BRAZIL (2002)', '12401997. CANADA (1997)',
       '12402004. CANADA (2004)', '75601999. SWITZERLAND (1999)',
       '75602003. SWITZERLAND (2003)', '15201999. CHILE (1999)',
       '15202005. CHILE (2005)', '20301996. CZECH REPUBLIC (1996)',
       '20302002. CZECH REPUBLIC (2002)',
       '27612002. GERMANY (2002 Telephone)',
       '27622002. GERMANY (2002 Mail-Back)', '27601998. GERMANY (1998)',
       '20801998. DENMARK (1998)', '20802001. DENMARK (2001)',
       '72401996. SPAIN (1996)', '72402000. SPAIN (2000)',
       '72402004. SPAIN (2004)', '24602003. FINLAND (2003)',
       '25002002. FRANCE (2002)', '82601997. GREAT BRITAIN (1997)',
       '82602005. GREAT BRITAIN (2005)', '34401998. HONG KONG (1998)',
       '34402000. HONG KONG (2000)', '34402004. HONG KONG (2004)',
       '34801998. HUNGARY (1998)', '34802002. HUNGARY (2002)',
       '37202002. IRELAND (2002)', '35201999. ICELAND (1999)',
       '35202003. ICELAND (2003)', '37601996. ISRAEL (1996)',
       '37602003. ISRAEL (2003)', '38002006. ITALY (2006)',
       '39201996. JAPAN (1996)', '39202004. JAPAN (2004)',
       '41702005. KYRGYZSTAN (2005)', '41002000. SOUTH KOREA (2000)',
       '41002004. SOUTH KOREA (2004)', '44001997. LITHUANIA (1997)',
       '48401997. MEXICO (1997)', '48402000. MEXICO (2000)',
       '48402003. MEXICO (2003)', '52801998. NETHERLANDS (1998)',
       '52802002. NETHERLANDS (2002)', '57801997. NORWAY (1997)',
       '57802001. NORWAY (2001)', '55401996. NEW ZEALAND (1996)',
       '55402002. NEW ZEALAND (2002)', '60402000. PERU (2000)',
       '60402001. PERU (2001)', '60402006. PERU (2006)',
       '60802004. PHILIPPINES (2004)', '61601997. POLAND (1997)',
       '61602001. POLAND (2001)', '62002002. PORTUGAL (2002)',
       '62002005. PORTUGAL (2005)', '64201996. ROMANIA (1996)',
       '64202004. ROMANIA (2004)', '64301999. RUSSIA (1999)',
       '64302000. RUSSIA (2000)', '64302004. RUSSIA (2004)',
       '70501996. SLOVENIA (1996)', '70502004. SLOVENIA (2004)',
       '75201998. SWEDEN (1998)', '75202002. SWEDEN (2002)',
       '76402001. THAILAND (2001)', '15801996. TAIWAN (1996)',
       '15802001. TAIWAN (2001)', '15802004. TAIWAN (2004)',
       '80401998. UKRAINE (1998)', '84001996. UNITED STATES (1996)',
       '84002004. UNITED STATES (2004)'], dtype=object)

In [369]:
CSES_int_final["IMD5024_3"]

0         9999. MISSING
1         9999. MISSING
2         9999. MISSING
3         9999. MISSING
4         9999. MISSING
              ...
316243             2016
316244             2016
316245             2016
316246             2016
316247             2016
Name: IMD5024_3, Length: 316248, dtype: object

In [354]:
# CSES_int_final["IMD5024_1"].value_counts()

99. MISSING      128257
10. OCTOBER       49034
09. SEPTEMBER     35394
05. MAY           20614
04. APRIL         18252
11. NOVEMBER      17990
07. JULY          12230
06. JUNE          11258
03. MARCH          9510
12. DECEMBER       5473
01. JANUARY        4594
02. FEBRUARY       2442
08. AUGUST         1200
Name: IMD5024_1, dtype: int64

In [356]:
# hmm - what do you when you have partial dates?
# some sort of hassle where you interpolate ... maybe easier to look up and fix if it's only one or two cases?

# precision here may be a bit spurious, but not harmful
#- where unclear, I take it using the strict (lazy) interpretation of term limits

# IMD5024 date discrepancies
# Year present, month not
#'30002009. GREECE (2009)':'16 September 2011'

# Year present, day not
# '04002008. AUSTRIA (2008)':1,
# '10002014. BULGARIA (2014)':12,
#        '27602005. GERMANY (2005)':22,
#        '30012015. GREECE (2015)':25,
# 37202011. IRELAND (2011)':24,
#        '35202009. ICELAND (2009)':12,
#'37602006. ISRAEL (2006)':28,
#        '42802011. LATVIA (2011)':2,
# '52802006. NETHERLANDS (2006)':22

## IMD1013 is problematic!
## basically requires a whole bunch of special handling


CSES_int_final.loc[CSES_int_final["IMD1003"]=='30002009. GREECE (2009)',"IMD5024_2"]=16
CSES_int_final.loc[CSES_int_final["IMD1003"]=='30002009. GREECE (2009)',"IMD5024_1"]="09. SEPTEMBER"
CSES_int_final.loc[CSES_int_final["IMD1003"]=='04002008. AUSTRIA (2008)',"IMD5024_2"]=1
CSES_int_final.loc[CSES_int_final["IMD1003"]=='10002014. BULGARIA (2014)',"IMD5024_2"]=12
CSES_int_final.loc[CSES_int_final["IMD1003"]=='27602005. GERMANY (2005)',"IMD5024_2"]=22
CSES_int_final.loc[CSES_int_final["IMD1003"]=='30012015. GREECE (2015)',"IMD5024_2"]=25
CSES_int_final.loc[CSES_int_final["IMD1003"]=='37202011. IRELAND (2011)',"IMD5024_2"]=24
CSES_int_final.loc[CSES_int_final["IMD1003"]=='35202009. ICELAND (2009)',"IMD5024_2"]=12
CSES_int_final.loc[CSES_int_final["IMD1003"]=='37602006. ISRAEL (2006)',"IMD5024_2"]=28
CSES_int_final.loc[CSES_int_final["IMD1003"]=='42802011. LATVIA (2011)',"IMD5024_2"]=2
CSES_int_final.loc[CSES_int_final["IMD1003"]=='52802006. NETHERLANDS (2006)',"IMD5024_2"]=22

In [210]:
CSES_int_final["IMD1013_Y"].replace(missing_dict).astype(float).groupby(CSES_int_final["IMD1003"]).apply(lambda x: x.max()-x.min()).dropna().sort_values()

# at most a year apart

IMD1003
00802005. ALBANIA (2005)             0.0
48402015. MEXICO (2015)              0.0
49902012. MONTENEGRO (2012)          0.0
52801998. NETHERLANDS (1998)         0.0
52802002. NETHERLANDS (2002)         0.0
                                    ...
15202009. CHILE (2009)               1.0
15202017. CHILE (2017)               1.0
49902016. MONTENEGRO (2016)          1.0
05621999. BELGIUM-WALLONIA (1999)    1.0
20802007. DENMARK (2007)             1.0
Name: IMD1013_Y, Length: 190, dtype: float64

In [212]:
CSES_int_final["IMD1013_M"].replace(missing_dict).replace(date_replace_dict).astype(float).groupby(CSES_int_final["IMD1003"]).apply(lambda x: x.max()-x.min()).dropna().sort_values()

IMD1003
00802005. ALBANIA (2005)         0.0
48402000. MEXICO (2000)          0.0
48401997. MEXICO (1997)          0.0
44001997. LITHUANIA (1997)       0.0
41002016. SOUTH KOREA (2016)     0.0
                                ...
64301999. RUSSIA (1999)         11.0
68802012. SERBIA (2012)         11.0
03602013. AUSTRALIA (2013)      11.0
49902016. MONTENEGRO (2016)     11.0
52802006. NETHERLANDS (2006)    11.0
Name: IMD1013_M, Length: 182, dtype: float64

In [378]:
# int(np.ceil(np.random.rand(100,1)*30))

# np.random.rand(100,1)


# CSES_int_final


# election_dates.loc[CSES_int_final["IMD1003"]]+pd.Timedelta('25 days')

In [390]:
def get_date(x):
    if pd.notnull(x):
        return str(int(x))
    else:
        return "nan"

missing_narrow = ["99. MISSING","9999. MISSING",'96. [SEE ELECTION STUDY NOTES]']
missing_narrow_dict = dict(zip(missing_narrow,[np.nan]*len(missing_narrow))) 

# '99. MISSING'
missing = ["96. NOT APPLICABLE: NO SECOND ROUND","99. MISSING","9996. NOT APPLICABLE: NO SECOND ROUND","9999. MISSING","96. [SEE ELECTION STUDY NOTES]"]
missing_dict = dict(zip(missing,[np.nan]*len(missing)))


def is_missing(x):
    return (x == "99. MISSING")|(x=="9999. MISSING")|(x=="96. [SEE ELECTION STUDY NOTES]")
    

def create_date_column(base_int):
    
    d_str,m_str,y_str = tuple(base_date_dict[base_int])
    date_temp = CSES_int_final[[base_int+d_str,base_int+m_str,base_int+y_str]]
    #.replace(date_replace_dict).replace(missing_dict).astype('object')
    
    # only occurs in IMD1012 and is consistent for all date compoents
    non_applicable = date_temp[[base_int+d_str,base_int+m_str,base_int+y_str]]\
        .apply(lambda x: (x == "96. NOT APPLICABLE: NO SECOND ROUND")|(x=="9996. NOT APPLICABLE: NO SECOND ROUND")).any(axis=1)
    # missing values appear only in IMD1013 and IMD5024
    # no overlap - but script will break if you add a variable that does have overlap!

    
    year_and_month_present_missing_day = date_temp[base_int+d_str].apply(lambda x: is_missing(x))&\
                                        date_temp[base_int+m_str].apply(lambda x: not is_missing(x))&\
                                        date_temp[base_int+y_str].apply(lambda x: not is_missing(x))
    
    date_temp[base_int+d_str][year_and_month_present_missing_day]==18
    
    year_or_month_missing = date_temp[base_int+m_str].apply(lambda x: is_missing(x))|\
                            date_temp[base_int+y_str].apply(lambda x: is_missing(x))
    
    date_temp = date_temp.replace(date_replace_dict).replace(missing_dict).astype('object')    
    

#    date_temp = date_temp.replace(date_replace_dict).replace({"96. NOT APPLICABLE: NO SECOND ROUND","9996. NOT APPLICABLE: NO SECOND ROUND"])
    
#     # replace missing day with random day from 1-30
#     date_temp[base_int+d_str]= date_temp[base_int+d_str].apply(lambda x: x if pd.notnull(x) else int(np.ceil(np.random.rand())*30)  )

#         # replace missing day with random day from 1-30
#     date_temp[base_int+m_str]= date_temp[base_int+m_str].apply(lambda x: x if pd.notnull(x) else int(np.ceil(np.random.rand())*12)  )
    
    # if month and year present, but day missing -> replace with 18th (highest frequency, mid month, better than trying to recretate the exact dist)
    # if month or year not present -> replace with 25 days after election
    
    # specify which of these holds in non-resp
    
    # you need distinct handling for cases where it's legitimately missing
#     ["96. NOT APPLICABLE: NO SECOND ROUND","99. MISSING","9996. NOT APPLICABLE: NO SECOND ROUND","9999. MISSING"]

    
    null_date_rows = date_temp.isnull().any(axis=1)
    date = date_temp[base_int+d_str].apply(get_date).astype(str)+"\\"+\
        date_temp[base_int+m_str].apply(get_date).astype(str)+"\\"+\
        date_temp[base_int+y_str].apply(get_date).astype(str)
    date[null_date_rows] = np.nan
    
    merged_date = pd.to_datetime(date, format = "%d\%m\%Y")
    if base_int=="IMD1013": ## impute using election day
        merged_date[year_or_month_missing] = election_dates.loc[CSES_int_final["IMD1003"]][year_or_month_missing.values]+\
                                                pd.Timedelta('25 days')
    
    non_resp = merged_date.copy()
    non_resp = np.nan
    non_resp= pd.Series(index=  merged_date.index)
    non_resp[:] =np.nan
    non_resp[year_and_month_present_missing_day] = "year_and_month_present_missing_day"
    if base_int=="IMD1013": ## impute using election day
        non_resp[year_or_month_missing] = "year_or_month_missing"
    else:
        non_resp[year_or_month_missing] = "missing"
    
    non_resp[non_applicable] = "non_applicable"
    non_resp = non_resp.astype('category')
    
    
    return merged_date, non_resp
    

# IMD1011_X
# DATE 1ST ROUND ELECTION BEGAN
base_int = "IMD1011"
IMD1011_date,IMD1011_date_non_resp = create_date_column(base_int)
election_dates = IMD1011_date.groupby(CSES_int_final["IMD1003"]).first()

# IMD1012_X
# DATE 2ND ROUND ELECTION BEGAN
base_int = "IMD1012"
IMD1012_date,IMD1012_date_non_resp = create_date_column(base_int)

# DATE QUESTIONNAIRE ADMINISTERED
base_int = "IMD1013"
IMD1013_date,IMD1013_date_non_resp = create_date_column(base_int)

# IMD5024_X
# DATE ELECTION SCHEDULED
base_int = "IMD5024"
IMD5024_date,IMD5024_date_non_resp = create_date_column(base_int)

# IMD5025_X
# DATE ELECTION HELD
base_int = "IMD5025"
IMD5025_date,IMD5025_date_non_resp = create_date_column(base_int)

In [389]:
# %debug

# CSES_int_final["IMD1011_D"].dtype.categories.dtype.name
#.categories.dtype

# IMD1013_date[1].value_counts()
# IMD1013_date[0]
# IMD1013_date_non_resp.value_counts()


(CSES_int_final[["IMD5024_2","IMD5024_1","IMD5024_3",]]=='96. [SEE ELECTION STUDY NOTES]').sum()

IMD5024_2    6099
IMD5024_1       0
IMD5024_3       0
dtype: int64

In [382]:
# average_questionnaire_dates_by_es = IMD1013_date.groupby(CSES_int_final["IMD1003"]).apply(lambda x: (x-pd.to_datetime("1/1/2010")).mean()+pd.to_datetime("1/1/2010"))
# range_questionnaire_dates_by_es = IMD1013_date.groupby(CSES_int_final["IMD1003"]).apply(lambda x: (x-pd.to_datetime("1/1/2010")).max() - (x-pd.to_datetime("1/1/2010")).min())
# range_questionnaire_dates_by_es.dropna().sort_values().tail(50)
# ### range goes up to 257 days
# std_questionnaire_dates_by_es = IMD1013_date.groupby(CSES_int_final["IMD1003"]).apply(lambda x: (x-pd.to_datetime("1/1/2010")).std())
# std_questionnaire_dates_by_es.sort_values().dt.days.replace(0,np.nan).dropna().mean()
# #.replace({pd.Timedelta('0 days'):np.nan}).dropna()
# ### std goes up to 74, mean of 10.44 days

# average_questionnaire_dates_by_es[average_questionnaire_dates_by_es.isnull()]

In [386]:
# CSES_int_final[CSES_int_final["IMD1003"]=="27602005. GERMANY (2005)"]["IMD1013_Y"].value_counts()

In [383]:
# (IMD1013_date - IMD1011_date).median(),(IMD1013_date - IMD1011_date).mean(),

# median 25 days after, mean 53 days after

In [384]:
# CSES_int_final["IMD1013_D"].value_counts()

In [385]:
# # DATE 1ST ROUND ELECTION BEGAN
# base_int = "IMD1011"
# d_str = "_D"
# m_str = "_M"
# y_str = "_Y"
# create_date_column(base_int,d_str,m_str,y_str)

In [190]:
# IMD1011_X
# DATE 1ST ROUND ELECTION BEGAN

# IMD1012_X
# DATE 2ND ROUND ELECTION BEGAN

# IMD1013_X
# DATE QUESTIONNAIRE ADMINISTERED

# IMD5024_X
# DATE ELECTION SCHEDULED

# IMD5025_X
# DATE ELECTION HELD

dmy_sub = ["_D","_M","_Y"]
num_sub = ["_2","_1","_3"]

flatten = lambda l: [item for sublist in l for item in sublist]
base_date_dict = {"IMD1011":dmy_sub,"IMD1012":dmy_sub,"IMD1013":dmy_sub,"IMD5024":num_sub,"IMD5025":num_sub}
base_date_dict_names = {"IMD1011":"DATE 1ST ROUND ELECTION BEGAN","IMD1012":"DATE 2ND ROUND ELECTION BEGAN",
                        "IMD1013":"DATE QUESTIONNAIRE ADMINISTERED","IMD5024":"DATE ELECTION SCHEDULED",
                        "IMD5025":"DATE ELECTION HELD"}


def get_date(x):
    if pd.notnull(x):
        return str(int(x))
    else:
        return "nan"
    
def create_date_column(ser):
    d_str,m_str,y_str = tuple(base_date_dict[ser.name])
    
    date_temp = input_df[[ser.name+d_str,ser.name+m_str,ser.name+y_str]].copy()
    date_temp_non_resp = date_temp.apply(lambda x: x if not isnum(x) and re.match(pattern,x) else np.nan).astype('category')
    
    null_date_rows = input_df[[ser.name+d_str,ser.name+m_str,ser.name+y_str]].isnull().any(axis=1)
    date = input_df[ser.name+d_str].apply(get_date)+"\\"+input_df[ser.name+m_str].apply(get_date)+"\\"+input_df[ser.name+y_str].apply(get_date)
    date[null_date_rows] = np.nan
    
    
    
    non_resp = ser.apply(lambda x: x if not isnum(x) and re.match(pattern,x) else np.nan).astype('category').copy()    
    non_resp.name = ser.name+"_DK"
    non_resp_cont_inf = non_resp.value_counts().sort_index().to_dict()    
    
    
    return pd.to_datetime(date, format = "%d\%m\%Y")    
    
def add_manifest_entry(resp_name,variable,response_type,resp_rows,non_resp_rows,resp_cont_inf,variable_type):
    # response_type = "response"|"nonresponse"
    #
    # get next manifest index
    if process_variable_manifest.shape[0]==0:
        man_ind = 0
    else:
        man_ind = np.max(process_variable_manifest.index)+1
    if variable_type=="date":
        process_variable_manifest.loc[man_ind] = [resp_name,
                                                  [resp_name+x for x in base_date_dict[resp_name]],
                                                  base_date_dict_names[resp_name],
                                                  response_type,
                                                  resp_rows,
                                                  non_resp_rows,
                                                  resp_cont_inf,
                                                  variable_type,
                                                  variable_manifest.set_index("index").loc[variable,"variable structural type"],

                                                 ]            
    else:
        process_variable_manifest.loc[man_ind] = [resp_name,
                                                  variable,
                                                  variable_manifest.set_index("index").loc[variable,"descr"],
                                                  response_type,
                                                  resp_rows,
                                                  non_resp_rows,
                                                  resp_cont_inf,
                                                  variable_type,
                                                  variable_manifest.set_index("index").loc[variable,"variable structural type"],

                                                 ]

In [387]:
# re.match(pattern,'99. MISSING')

In [191]:
pattern = "(9{2,8}\d?\.(00)?\.?)|(.*\[SEE ELECTION STUDY NOTES\])|(.*DON'T KNOW)|(.*REFUSED)|(.*NOT APPLICABLE)|(.*MISSING)|(.*Transition Periods)"

seminumeric_replace_dict = {"10. Democratic":10,"-10. AUTOCRATIC":-10,"00.00 THERE IS NO THRESHOLD":0,
                           "00. LEFT":0.0,"10. RIGHT":10.0}

date_replace_dict = {'01. JANUARY':1, '02. FEBRUARY':2, '03. MARCH':3, '04. APRIL':4, '05. MAY':5, '06. JUNE':6,
                     '07. JULY':7, '08. AUGUST':8, '09. SEPTEMBER':9, '10. OCTOBER':10, '11. NOVEMBER':11, '12. DECEMBER':12}

def isnum(x):
    return str(x).replace('.','',1).replace('-','',1).isdigit()

def list_categories(ser):
    return "|".join([str(x) for x in ser.cat.categories])


def process_var(ser,var_type):
    non_resp = ser.apply(lambda x: x if not isnum(x) and re.match(pattern,x) else np.nan).astype('category').copy()    
    non_resp.name = ser.name+"_DK"
    non_resp_cont_inf = non_resp.value_counts().sort_index().to_dict()
    
    if var_type == "seminumeric":
        
        resp=ser.copy()
        
        if ser.dtype.name=='object':
            resp = resp.replace(seminumeric_replace_dict)
        # FIX LATER
        
        resp = resp.apply(lambda x: x if isnum(x) else np.nan).astype('float32').copy()
        
        assert (non_resp.notnull().sum()+resp.notnull().sum()) == ser.shape[0]
        
        resp.name = ser.name+"_NUM"
        resp_cont_inf = (resp.min(),resp.max())
        
        
        return non_resp,resp,non_resp_cont_inf,resp_cont_inf
    
    elif var_type == "ordinal":
        
        resp = ser.astype('category').cat.remove_categories(non_resp.cat.categories)
        resp_cont_inf = dict(zip(resp.cat.categories,
                             range(0,len(resp.cat.categories))))
        
        resp = resp.cat.codes.replace(-1,np.nan).astype('float32')
        
        assert (non_resp.notnull().sum()+resp.notnull().sum()) == ser.shape[0]
        
        resp.name = ser.name+"_ORD"
        
        return non_resp,resp,non_resp_cont_inf,resp_cont_inf
    
    elif var_type == "dummy":
        
        resp = ser.astype('category').cat.remove_categories(non_resp.cat.categories)
        resp_cont_inf = resp.value_counts().sort_index().to_dict()
        
        resp = pd.get_dummies( resp, prefix = ser.name )
        resp.name = ser.name
        
        ## should we change this to numbers???
        
        assert (non_resp.notnull().sum()+resp.any(axis=1).sum()) == ser.shape[0]
        
#         resp.name = ser.name+"_DUM"
        
        
        return non_resp,resp,non_resp_cont_inf,resp_cont_inf    
    
    elif var_type == "party":
        
        ## change to replacing with partyfacts_id
        
#         resp = ser.astype('category').cat.remove_categories(non_resp.cat.categories).apply(lambda x: float(x[0:7]) if pd.notnull() else np.nan).astype('float32')
        resp = ser.apply(lambda x: cses_to_partyfacts_final.loc[x]).astype(float)
        resp_cont_inf = (resp.min(),resp.max())
        resp.name = ser.name+"_PTY"

    
        non_resp = ser.copy()
        non_resp[resp.notnull()]=np.nan
        #ser.apply(lambda x: x if not isnum(x) and re.match(pattern,x) else np.nan).astype('category').copy()    
        non_resp.name = ser.name
        non_resp.name = non_resp.name+"_DK"
        non_resp_cont_inf = non_resp.value_counts().sort_index().to_dict()    
        
        
        # what information would you really want here for party data?
        # should I change this with partyfacts_ids - go for min/max?
        #resp.value_counts().sort_index().to_dict()
        
#         resp.name = ser.name
        
        ## should we change this to numbers???
        
        assert (non_resp.notnull().sum()+resp.notnull().sum()) == ser.shape[0]
        

        
        
        return non_resp,resp,non_resp_cont_inf,resp_cont_inf
    
    elif var_type == "date":
        
        resp=ser.astype('category').cat.remove_categories(non_resp.cat.categories)
        
        if (resp.dtype.name=='object') or (resp.dtype.name=='category' and resp.cat.categories.dtype!='int64'):
            resp = resp.replace(date_replace_dict)
                
                
#         base_int = ser.name
        resp.name = ser.name.split("_")[0]   
                
        resp, non_resp = create_date_column(resp.astype('float32'))
        
        
        
        
        
        # what information would you really want here for party data?
        resp_cont_inf = resp.value_counts().sort_index().to_dict()
        
        
        
        ## should we change this to numbers???
        
        assert (non_resp.notnull().sum()+resp.notnull().sum()) == ser.shape[0]
        
        resp.name = ser.name+"_DAT"
        
        
        return non_resp,resp,non_resp_cont_inf,resp_cont_inf    
    
        ## some final processing here to get datetimes
        # maybe separate variables?
        
    elif var_type == "meta":
                        
        resp = ser.astype('category').cat.remove_categories(non_resp.cat.categories)
        
        # what information would you really want here for party data?
        resp_cont_inf = resp.value_counts().sort_index().to_dict()
        
#         resp = pd.get_dummies( resp, prefix = ser.name )
        resp.name = ser.name
        
        ## should we change this to numbers???
        
        assert (non_resp.notnull().sum()+resp.notnull().sum()) == ser.shape[0]
        
        resp.name = ser.name+"_MET"
        
        
        return non_resp,resp,non_resp_cont_inf,resp_cont_inf           

    
    # Date?

In [192]:
# maybe also want "display names" (descriptions)
    
def process_dataset(input_df,process_variable_manifest):
    resp_df     = pd.DataFrame()
    non_resp_df = pd.DataFrame()

    for variable_type in ["seminumeric","ordinal","dummy","date","meta","drop","party"]:
    #["date","meta","ordinal","drop"]:
    #["seminumeric","ordinal","dummy"]:
        specific_vars = set(input_df.columns).intersection(set(variable_manifest[variable_manifest["variable type"]==variable_type]["index"].values))
        if variable_type=="drop":
            continue
            


        for variable in specific_vars:
            ## only trigger on *one* of the date variable components
            if variable_type=="date" and (variable not in [x+base_date_dict[x][0] for x in base_date_dict.keys()]):
                continue
            
            (non_resp,resp,non_resp_cont_inf,resp_cont_inf) = process_var(input_df[variable],
                                                                          variable_type)






            # add non_resp to relevant dataframe    
            non_resp_rows = non_resp.notnull().sum()
            non_resp_df[non_resp.name] = non_resp

            if isinstance(resp,pd.Series):

                # add resp to relevant dataframe    
                resp_rows = resp.notnull().sum()
                resp_df[resp.name] = resp

                add_manifest_entry(resp.name,variable,"response",resp_rows,non_resp_rows,resp_cont_inf,variable_type)
#                 # get next manifest index
#                 if process_variable_manifest.shape[0]==0:
#                     man_ind = 0
#                 else:
#                     man_ind = np.max(process_variable_manifest.index)+1

#                 process_variable_manifest.loc[man_ind] = [resp.name,
#                                                           variable,
#                                                           variable_manifest.set_index("index").loc[variable,"descr"],
#                                                           "response",
#                                                           resp_rows,
#                                                           non_resp_rows,
#                                                           resp_cont_inf,
#                                                           variable_type,
#                                                           variable_manifest.set_index("index").loc[variable,"variable structural type"],

#                                                          ]
            else:
                for col in resp.columns:

                    # add resp to relevant dataframe    
                    resp_rows = resp.any(axis=1).sum()
                    resp_df[resp[col].name] = resp[col]

                    add_manifest_entry(resp.name,variable,"response",resp_rows,non_resp_rows,resp_cont_inf,variable_type)
#                     # get next manifest index
#                     if process_variable_manifest.shape[0]==0:
#                         man_ind = 0
#                     else:
#                         man_ind = np.max(process_variable_manifest.index)+1

#                     process_variable_manifest.loc[man_ind] = [resp[col].name,
#                                                               variable,
#                                                               variable_manifest.set_index("index").loc[variable,"descr"],
#                                                               "response",
#                                                               resp_rows,
#                                                               non_resp_rows,
#                                                               resp_cont_inf,
#                                                               variable_type,
#                                                               variable_manifest.set_index("index").loc[variable,"variable structural type"],

#                                                              ]            

            add_manifest_entry(non_resp.name,variable,"non-response",resp_rows,non_resp_rows,resp_cont_inf,variable_type)
#             # get next manifest index
#             if process_variable_manifest.shape[0]==0:
#                 man_ind = 0
#             else:
#                 man_ind = np.max(process_variable_manifest.index)+1    

#             process_variable_manifest.loc[man_ind] = [non_resp.name,
#                                                       variable,
#                                                       variable_manifest.set_index("index").loc[variable,"descr"],
#                                                       "non-response",
#                                                       resp_rows,
#                                                       non_resp_rows,
#                                                       non_resp_cont_inf,
#                                                       variable_type,
#                                                       variable_manifest.set_index("index").loc[variable,"variable structural type"],

#                                                      ]    
    return resp_df,non_resp_df,process_variable_manifest
    
# ["new_variable_name",
# "source_variable_name",
# "response/non-response",
# "resp_rows",
# "non_resp_rows",
# "contents_inf",
# "variable type",
# "variable structural type"]    
    
    

# spit out

# response column/s
# non-response columns

# create meaningful names for each
# record in manifesto dataframe

# source variable|resp/non-respone|new name|categories inf|rows-resp|rows-non-resp

# categories inf
#  non-resp = sorted category set
#  semi-numeric = min,max
#  ordinal = code -> value dict
#  dummy = largest category??

# balance of rows of resp/non-resp?


# SHORTNAME!

# dummy variables - useful to know what the largest category is (in case used as 'base' - can you do that when you have missing values?)

# process_variable_manifest

In [193]:
%%time


input_df = respondent_vars_level_dataset.copy()

process_variable_manifest = pd.DataFrame(columns = ["new_variable_name",
                                                    "source_variable_name",
                                                    "description",
                                                    "response/non-response",
                                                    "resp_rows",
                                                    "non_resp_rows",
                                                    "contents_inf",
                                                    "variable type",
                                                    "variable structural type"])


resp_df,nonresp_df,process_variable_manifest = process_dataset(input_df,process_variable_manifest)
process_variable_manifest

ValueError: invalid literal for int() with base 10: '99. MISSING'

In [194]:
%debug

> <ipython-input-190-99f950ab0943>(28)get_date()
     26 def get_date(x):
     27     if pd.notnull(x):
---> 28         return str(int(x))
     29     else:
     30         return "nan"

ipdb> up
> c:\users\marios\documents\github\bes_analysis\bes_analysis_code\pandas\_libs\lib.pyx(2327)pandas._libs.lib.map_infer()

ipdb> up
> c:\programdata\anaconda3\envs\bes_analysis\lib\site-packages\pandas\core\base.py(1154)_map_values()
   1152
   1153         # mapper is a function
-> 1154         new_values = map_f(values, mapper)
   1155
   1156         return new_values

ipdb> down
> c:\users\marios\documents\github\bes_analysis\bes_analysis_code\pandas\_libs\lib.pyx(2327)pandas._libs.lib.map_infer()

ipdb> down
> <ipython-input-190-99f950ab0943>(28)get_date()
     26 def get_date(x):
     27     if pd.notnull(x):
---> 28         return str(int(x))
     29     else:
     30         return "nan"

ipdb> x
'99. MISSING'
ipdb> up
> c:\users\marios\documents\github\bes_analysis\bes_analysis_code\pandas\_libs\lib.pyx(2327)pandas._libs.lib.map_infer()

ipdb> quit

In [156]:
%%time


input_df = election_study_level_dataset.copy()

# process_variable_manifest = pd.DataFrame(columns = ["new_variable_name",
#                                                     "source_variable_name",
#                                                     "description",
#                                                     "response/non-response",
#                                                     "resp_rows",
#                                                     "non_resp_rows",
#                                                     "contents_inf",
#                                                     "variable type",
#                                                     "variable structural type"])


es_resp_df,es_nonresp_df,process_variable_manifest = process_dataset(input_df,process_variable_manifest)
process_variable_manifest

Wall time: 2.74 s

,new_variable_name,source_variable_name,description,response/non-response,resp_rows,non_resp_rows,contents_inf,variable type,variable structural type
0,IMD2001_1_NUM,IMD2001_1,AGE OF RESPONDENT (IN YEARS),response,309649,6599,"(15.0, 115.0)",seminumeric,respondent
1,IMD2001_1_DK,IMD2001_1,AGE OF RESPONDENT (IN YEARS),non-response,309649,6599,"{'9997. REFUSED': 656, '9998. DON'T KNOW': 119...",seminumeric,respondent
2,IMD1014_2_NUM,IMD1014_2,INTERVIEW TIMING - NUMBER OF DAYS BETWEEN INTE...,response,35437,280811,"(1.0, 275.0)",seminumeric,respondent
3,IMD1014_2_DK,IMD1014_2,INTERVIEW TIMING - NUMBER OF DAYS BETWEEN INTE...,non-response,35437,280811,"{'9995. NOT ASCERTAINED': 5409, '9996. NOT APP...",seminumeric,respondent
4,IMD1014_1_NUM,IMD1014_1,INTERVIEW TIMING - NUMBER OF DAYS BETWEEN INTE...,response,281024,35224,"(0.0, 362.0)",seminumeric,respondent
...,...,...,...,...,...,...,...,...,...
416,IMD5009_1_DK,IMD5009_1,PARTY OF THE PRESIDENT BEFORE,non-response,104,91,{'1120101. BLR - A. Lukashenko (Independent)':...,party,country
417,IMD5008_2_PTY,IMD5008_2,PARTY OF THE PRIME MINISTER AFTER,response,142,53,"(49.0, 6647.0)",party,country
418,IMD5008_2_DK,IMD5008_2,PARTY OF THE PRIME MINISTER AFTER,non-response,142,53,{'3760011. ISR - The Consolidation (Likud) - Y...,party,country
419,IMD5009_2_PTY,IMD5009_2,PARTY OF THE PRESIDENT AFTER,response,104,91,"(6.0, 8130.0)",party,country
420,IMD5009_2_DK,IMD5009_2,PARTY OF THE PRESIDENT AFTER,non-response,104,91,{'1120101. BLR - A. Lukashenko (Independent)':...,party,country

In [157]:
%%time

input_df = party_level_dataset.copy()

party_resp_df,party_nonresp_df,process_variable_manifest = process_dataset(input_df,process_variable_manifest)

Wall time: 679 ms

In [158]:
party_resp_df

,IMD5004_NUM,IMD5012_NUM,IMD5001_NUM,IMD5031_NUM,IMD5002_NUM,IMD5029_NUM,IMD5003_NUM,IMD5005_NUM,IMD5011_1. ECOLOGY PARTIES,IMD5011_10. NATIONAL PARTIES,...,IMD5011_5. LEFT LIBERAL PARTIES,IMD5011_6. LIBERAL PARTIES,IMD5011_7. RIGHT LIBERAL PARTIES,IMD5011_8. CHRISTIAN DEMOCRATIC PARTIES,IMD5011_9. CONSERVATIVE PARTIES,IMD5011_90. OTHER,IMD5011_98. NO IDEOLOGICAL FAMILY MENTIONED,IMD1003_MET,partyfacts_id_MET,party_letter_MET
0,NaN,6.0,44.060001,12.0,40.000000,0.0,NaN,NaN,0,0,...,0,0,0,0,1,0,0,00802005. ALBANIA (2005),190,A
1,54.169998,4.0,37.400002,0.0,43.849998,21.0,32.720001,NaN,0,0,...,1,0,0,0,0,0,0,03202015. ARGENTINA (2015),2530,A
2,38.099998,4.5,38.700001,NaN,33.099998,NaN,36.099998,NaN,0,0,...,0,0,0,0,0,0,0,03601996. AUSTRALIA (1996),424,A
3,45.000000,6.0,40.470001,14.0,50.000000,14.0,43.369999,NaN,0,0,...,0,0,1,0,0,0,0,03602004. AUSTRALIA (2004),1998,A
4,45.000000,3.0,43.380001,21.0,55.330002,0.0,40.299999,NaN,0,0,...,0,0,0,0,0,0,0,03602007. AUSTRALIA (2007),424,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.76,0,0,...,0,0,0,0,0,1,0,64302004. RUSSIA (2004),7409,I
1720,NaN,8.0,4.940000,0.0,0.000000,0.0,NaN,NaN,0,0,...,0,0,0,1,0,0,0,70302016. SLOVAKIA (2016),63,I
1733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,75202006. SWEDEN (2006),1240,I
1734,NaN,2.0,3.120000,0.0,0.000000,0.0,NaN,NaN,0,0,...,0,0,0,0,0,1,0,75202014. SWEDEN (2014),1240,I
1742,NaN,4.0,0.250000,0.0,0.000000,0.0,NaN,NaN,0,0,...,0,0,0,0,0,0,0,79202011. TURKEY (2011),1740,I

In [152]:
variable_manifest[variable_manifest["index"]=="IMD5012_A"]

CSES_int_final["IMD5012_A"].value_counts()

7.0                   69820
3.0                   52128
4.0                   44562
6.0                   40644
5.0                   40582
8.0                   24469
99. MISSING           14138
9.0                   12540
1.0                    4738
2.0                    4141
4.5                    2971
10. RIGHT              2506
00. LEFT               2000
97. NOT APPLICABLE     1009
Name: IMD5012_A, dtype: int64

In [146]:
process_variable_manifest.tail(50)

,new_variable_name,source_variable_name,description,response/non-response,resp_rows,non_resp_rows,contents_inf,variable type,variable structural type
373,IMD1012_D_DAT,IMD1012_D,DATE 2ND ROUND ELECTION BEGAN - DAY,response,31,164,"{1.0: 1, 3.0: 1, 4.0: 2, 5.0: 2, 6.0: 2, 7.0: ...",date,country
374,IMD1012_D_DK,IMD1012_D,DATE 2ND ROUND ELECTION BEGAN - DAY,non-response,31,164,{'96. NOT APPLICABLE: NO SECOND ROUND': 164},date,country
375,IMD5024_3_DAT,IMD5024_3,DATE ELECTION SCHEDULED - YEAR,response,115,80,"{2005.0: 2, 2006.0: 6, 2007.0: 9, 2008.0: 8, 2...",date,country
376,IMD5024_3_DK,IMD5024_3,DATE ELECTION SCHEDULED - YEAR,non-response,115,80,{'9999. MISSING': 80},date,country
377,IMD5025_2_DAT,IMD5025_2,DATE ELECTION HELD - DAY,response,192,3,"{1.0: 4, 2.0: 9, 3.0: 6, 4.0: 8, 5.0: 6, 6.0: ...",date,country
378,IMD5025_2_DK,IMD5025_2,DATE ELECTION HELD - DAY,non-response,192,3,{'96. [SEE ELECTION STUDY NOTES]': 3},date,country
379,IMD5025_1_DAT,IMD5025_1,DATE ELECTION HELD - MONTH,response,194,1,"{1.0: 6, 2.0: 3, 3.0: 20, 4.0: 21, 5.0: 22, 6....",date,country
380,IMD5025_1_DK,IMD5025_1,DATE ELECTION HELD - MONTH,non-response,194,1,{'96. [SEE ELECTION STUDY NOTES]': 1},date,country
381,IMD1012_Y_DAT,IMD1012_Y,DATE 2ND ROUND ELECTION BEGAN - YEAR,response,31,164,"{1996.0: 3, 1998.0: 2, 2000.0: 2, 2001.0: 2, 2...",date,country
382,IMD1012_Y_DK,IMD1012_Y,DATE 2ND ROUND ELECTION BEGAN - YEAR,non-response,31,164,{'9996. NOT APPLICABLE: NO SECOND ROUND': 164},date,country
383,IMD5025_3_DAT,IMD5025_3,DATE ELECTION HELD - YEAR,response,195,0,"{1996.0: 10, 1997.0: 6, 1998.0: 7, 1999.0: 6, ...",date,country
384,IMD5025_3_DK,IMD5025_3,DATE ELECTION HELD - YEAR,non-response,195,0,{},date,country
385,IMD1012_M_DAT,IMD1012_M,DATE 2ND ROUND ELECTION BEGAN - MONTH,response,31,164,"{1.0: 5, 3.0: 1, 4.0: 1, 5.0: 5, 6.0: 6, 10.0:...",date,country
386,IMD1012_M_DK,IMD1012_M,DATE 2ND ROUND ELECTION BEGAN - MONTH,non-response,31,164,{'96. NOT APPLICABLE: NO SECOND ROUND': 164},date,country
387,IMD1008_MOD_1_MET,IMD1008_MOD_1,ID COMPONENT - CSES MODULE 1,response,195,0,"{'00. NOT IN CSES MODULE 1': 156, '01. IN CSES...",meta,country
388,IMD1008_MOD_1_DK,IMD1008_MOD_1,ID COMPONENT - CSES MODULE 1,non-response,195,0,{},meta,country
389,IMD1008_MOD_2_MET,IMD1008_MOD_2,ID COMPONENT - CSES MODULE 2,response,195,0,"{'00. NOT IN CSES MODULE 2': 154, '01. IN CSES...",meta,country
390,IMD1008_MOD_2_DK,IMD1008_MOD_2,ID COMPONENT - CSES MODULE 2,non-response,195,0,{},meta,country
391,IMD1004_MET,IMD1004,ID VARIABLE - ELECTION STUDY (ALPHABETIC POLITY),response,195,0,"{'ALB_2005': 1, 'ARG_2015': 1, 'AUS_1996': 1, ...",meta,country
392,IMD1004_DK,IMD1004,ID VARIABLE - ELECTION STUDY (ALPHABETIC POLITY),non-response,195,0,{},meta,country
393,IMD1008_MOD_4_MET,IMD1008_MOD_4,ID COMPONENT - CSES MODULE 4,response,195,0,"{'00. NOT IN CSES MODULE 4': 150, '01. IN CSES...",meta,country
394,IMD1008_MOD_4_DK,IMD1008_MOD_4,ID COMPONENT - CSES MODULE 4,non-response,195,0,{},meta,country
395,IMD1001_MET,IMD1001,dataset,response,195,0,"{'CSES-IMD': 174, 'CSES-MODULE-5': 21}",meta,dataset
396,IMD1001_DK,IMD1001,dataset,non-response,195,0,{},meta,dataset
397,IMD1008_MOD_3_MET,IMD1008_MOD_3,ID COMPONENT - CSES MODULE 3,response,195,0,"{'00. NOT IN CSES MODULE 3': 145, '01. IN CSES...",meta,country
398,IMD1008_MOD_3_DK,IMD1008_MOD_3,ID COMPONENT - CSES MODULE 3,non-response,195,0,{},meta,country
399,IMD1002_VER_MET,IMD1002_VER,DATASET VERSION,response,195,0,"{'VER2019-OCT-17': 174, 'VER2020-MAY-14': 21}",meta,dataset
400,IMD1002_VER_DK,IMD1002_VER,DATASET VERSION,non-response,195,0,{},meta,dataset
401,IMD1006_MET,IMD1006,ID COMPONENT - POLITY CSES CODE,response,195,0,"{'0080': 1, '0320': 1, '0360': 5, '0400': 3, '...",meta,country
402,IMD1006_DK,IMD1006,ID COMPONENT - POLITY CSES CODE,non-response,195,0,{},meta,country
403,IMD1008_YEAR_MET,IMD1008_YEAR,ID COMPONENT - ELECTION YEAR,response,195,0,"{1996: 10, 1997: 6, 1998: 7, 1999: 6, 2000: 6,...",meta,country
404,IMD1008_YEAR_DK,IMD1008_YEAR,ID COMPONENT - ELECTION YEAR,non-response,195,0,{},meta,country
405,IMD1006_UN_MET,IMD1006_UN,ID COMPONENT - POLITY UN CODE,response,195,0,"{'008': 1, '032': 1, '036': 5, '040': 3, '056'...",meta,country
406,IMD1006_UN_DK,IMD1006_UN,ID COMPONENT - POLITY UN CODE,non-response,195,0,{},meta,country
407,IMD1006_NAM_MET,IMD1006_NAM,ID COMPONENT - POLITY NAME,response,195,0,"{'Albania': 1, 'Argentina': 1, 'Australia': 5,...",meta,country
408,IMD1006_NAM_DK,IMD1006_NAM,ID COMPONENT - POLITY NAME,non-response,195,0,{},meta,country
409,IMD1002_DOI_MET,IMD1002_DOI,DIGITAL OBJECT IDENTIFIER,response,195,0,"{'doi:10.7804/cses.imd.2019-10-17': 174, 'doi:...",meta,dataset
410,IMD1002_DOI_DK,IMD1002_DOI,DIGITAL OBJECT IDENTIFIER,non-response,195,0,{},meta,dataset
411,IMD1008_MOD_5_MET,IMD1008_MOD_5,ID COMPONENT - CSES MODULE 4,response,195,0,"{'00. NOT IN CSES MODULE 5': 174, '01. IN CSES...",meta,country
412,IMD1008_MOD_5_DK,IMD1008_MOD_5,ID COMPONENT - CSES MODULE 4,non-response,195,0,{},meta,country
413,IMD5008_1_DK_PTY,IMD5008_1,PARTY OF THE PRIME MINISTER BEFORE,response,142,53,"(49.0, 5941.0)",party,country
414,IMD5008_1_DK,IMD5008_1,PARTY OF THE PRIME MINISTER BEFORE,non-response,142,53,{'3760011. ISR - The Consolidation (Likud) - Y...,party,country
415,IMD5009_1_DK_PTY,IMD5009_1,PARTY OF THE PRESIDENT BEFORE,response,104,91,"(6.0, 8130.0)",party,country
416,IMD5009_1_DK,IMD5009_1,PARTY OF THE PRESIDENT BEFORE,non-response,104,91,{'1120101. BLR - A. Lukashenko (Independent)':...,party,country
417,IMD5008_2_DK_PTY,IMD5008_2,PARTY OF THE PRIME MINISTER AFTER,response,142,53,"(49.0, 6647.0)",party,country
418,IMD5008_2_DK,IMD5008_2,PARTY OF THE PRIME MINISTER AFTER,non-response,142,53,{'3760011. ISR - The Consolidation (Likud) - Y...,party,country
419,IMD5009_2_DK_PTY,IMD5009_2,PARTY OF THE PRESIDENT AFTER,response,104,91,"(6.0, 8130.0)",party,country
420,IMD5009_2_DK,IMD5009_2,PARTY OF THE PRESIDENT AFTER,non-response,104,91,{'1120101. BLR - A. Lukashenko (Independent)':...,party,country
421,IMD5004_NUM,IMD5004,PERCENT SEATS - UPPER HOUSE,response,277,993,"(0.0, 75.0)",seminumeric,party
422,IMD5004_DK,IMD5004,PERCENT SEATS - UPPER HOUSE,non-response,277,993,{'996. NOT APPLICABLE: UNICAMERAL SYSTEM': 586...,seminumeric,party

In [138]:
es_resp_df["IMD5012_ORD"].value_counts().sort_index()

0.0      61
1.0       1
2.0     105
3.0       1
4.0     145
5.0       1
6.0     166
7.0       2
8.0     163
9.0       1
10.0    161
11.0      1
12.0    171
13.0    111
14.0     61
15.0     11
16.0     14
Name: IMD5012_ORD, dtype: int64

In [140]:
CSES_int_final["IMD5012_A"].value_counts()

7.0                   69820
3.0                   52128
4.0                   44562
6.0                   40644
5.0                   40582
8.0                   24469
99. MISSING           14138
9.0                   12540
1.0                    4738
2.0                    4141
4.5                    2971
10. RIGHT              2506
00. LEFT               2000
97. NOT APPLICABLE     1009
Name: IMD5012_A, dtype: int64